export type UnipileMessagingStepLogChannel =
  | 'LINKEDIN_CONNECTION_REQUEST'
  | 'LINKEDIN_INMAIL'
  | 'LINKEDIN_MESSAGE'
  | 'LINKEDIN_ACTIVITY'
  | 'LINKEDIN_POST_COMMENT'
  | 'WHATSAPP_MESSAGE';
