export type UnipileMessagingStepLogChannel =
  | 'LINKEDIN_CONNECTION_REQUEST'
  | 'LINKEDIN_INMAIL'
  | 'LINKEDIN_MESSAGE'
  | 'LINKEDIN_ACTIVITY'
  | 'LINKEDIN_POST_COMMENT'
  | 'LINKEDIN_VOICE_NOTE'
  | 'LINKEDIN_PROFILE_VIEW'
  | 'LINKEDIN_FOLLOW'
  | 'LINKEDIN_POST_LIKE'
  | 'WHATSAPP_MESSAGE';
