export const panda = [
  {
    names: { first_name: 'Shweta', last_name: 'Pandey', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Shweta',
    last_name: 'Pandey',
    middle_name: null,
    middle_initial: null,
    full_name: 'Shweta Pandey',
    job_company_name: '',
    job_company_id: null,
    location_name: 'Mumbai',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/shweta-pandey-bab9a11a2',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'IT Engineer || Salesforce Developer Enthusiast || 5 × Salesforce Certified',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [
      {
        title: 'IT Engineer || Salesforce Developer Enthusiast || 5 × Salesforce Certified',
        network: 'linkedin',
        username: 'https://www.linkedin.com/in/shweta-pandey-bab9a11a2',
        is_primary: true,
        url: 'https://www.linkedin.com/in/shweta-pandey-bab9a11a2',
      },
    ],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Mumbai',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Salesforce Developer' }, company: { name: '' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/shweta-pandey-bab9a11a2',
    job_title: 'Salesforce Developer',
    unique_key_string: 'shwetapandey',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/shweta-pandey-bab9a11a2' },
    std_function: 'software',
    std_grade: 'entry',
    std_function_root: 'technology',
  },
  {
    names: { first_name: 'Anshul', last_name: 'Singhal', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Anshul',
    last_name: 'Singhal',
    middle_name: null,
    middle_initial: null,
    full_name: 'Anshul Singhal',
    job_company_name: '',
    job_company_id: null,
    location_name: 'Delhi, India',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/anshulsin08',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'Engineering @Salesforce',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [{ title: 'Engineering @Salesforce', network: 'linkedin', username: 'https://www.linkedin.com/in/anshulsin08', is_primary: true, url: 'https://www.linkedin.com/in/anshulsin08' }],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Delhi, India',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Lead Member of Technical Staff' }, company: { name: '' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/anshulsin08',
    job_title: 'Lead Member of Technical Staff',
    unique_key_string: 'anshulsinghal',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/anshulsin08' },
    std_function: 'technology',
    std_grade: 'entry',
    std_function_root: 'technology',
  },
  {
    names: { first_name: 'Vijay', last_name: 'Giri', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Vijay',
    last_name: 'Giri',
    middle_name: null,
    middle_initial: null,
    full_name: 'Vijay Giri',
    job_company_name: 'Salesforce || Ex-Flipkart, Acko || IIIT Lucknow',
    job_company_id: null,
    location_name: 'Bengaluru',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/vijay-giri-11b1b4154',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'SMTS at Salesforce || Ex-Flipkart, Acko || IIIT Lucknow',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [{ title: 'SMTS at Salesforce || Ex-Flipkart, Acko || IIIT Lucknow', network: 'linkedin', username: 'https://www.linkedin.com/in/vijay-giri-11b1b4154', is_primary: true, url: 'https://www.linkedin.com/in/vijay-giri-11b1b4154' }],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Bengaluru',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Senior Member of Technical Staff' }, company: { name: 'Salesforce || Ex-Flipkart, Acko || IIIT Lucknow' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/vijay-giri-11b1b4154',
    job_title: 'Senior Member of Technical Staff',
    unique_key_string: 'vijaygirisalesforce||exflipkartacko||iiitlucknow',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/vijay-giri-11b1b4154' },
    std_function: 'technology',
    std_grade: 'entry',
    std_function_root: 'technology',
  },
  {
    names: { first_name: 'Gaurav', last_name: 'Khandelwal', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Gaurav',
    last_name: 'Khandelwal',
    middle_name: null,
    middle_initial: null,
    full_name: 'Gaurav Khandelwal',
    job_company_name: 'Deloitte USI Consulting | Salesforce 6x Certified',
    job_company_id: null,
    location_name: 'Mumbai',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/gaurav-khandelwal-',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'Analyst at Deloitte USI Consulting | Salesforce 6x Certified',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [{ title: 'Analyst at Deloitte USI Consulting | Salesforce 6x Certified', network: 'linkedin', username: 'https://www.linkedin.com/in/gaurav-khandelwal-', is_primary: true, url: 'https://www.linkedin.com/in/gaurav-khandelwal-' }],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Mumbai',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Summary: 🌟Salesforce Developer & Analyst in Consulting 🌟 🔍 Crafting Solutions | 6x Certified Salesforce...' }, company: { name: 'Deloitte USI Consulting | Salesforce 6x Certified' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/gaurav-khandelwal-',
    job_title: 'Summary: 🌟Salesforce Developer & Analyst in Consulting 🌟 🔍 Crafting Solutions | 6x Certified Salesforce...',
    unique_key_string: 'gauravkhandelwaldeloitteusiconsulting|salesforce6xcertified',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/gaurav-khandelwal-' },
    std_function: 'software',
    std_grade: 'entry',
    std_function_root: 'technology',
  },
  {
    names: { first_name: 'Vinita', last_name: 'Chugh', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Vinita',
    last_name: 'Chugh',
    middle_name: null,
    middle_initial: null,
    full_name: 'Vinita Chugh',
    job_company_name: '',
    job_company_id: null,
    location_name: 'Mumbai',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/vinita-chugh-b83560205',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'Salesforce developer || 4X Salesforce Certified',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [{ title: 'Salesforce developer || 4X Salesforce Certified', network: 'linkedin', username: 'https://www.linkedin.com/in/vinita-chugh-b83560205', is_primary: true, url: 'https://www.linkedin.com/in/vinita-chugh-b83560205' }],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Mumbai',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Salesforce Developer' }, company: { name: '' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/vinita-chugh-b83560205',
    job_title: 'Salesforce Developer',
    unique_key_string: 'vinitachugh',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/vinita-chugh-b83560205' },
    std_function: 'software',
    std_grade: 'entry',
    std_function_root: 'technology',
  },
  {
    names: { first_name: 'Riddhi', last_name: 'Siddhpura', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Riddhi',
    last_name: 'Siddhpura',
    middle_name: null,
    middle_initial: null,
    full_name: 'Riddhi Siddhpura',
    job_company_name: '',
    job_company_id: null,
    location_name: 'Mumbai',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/riddhi-siddhpura-b6817a199',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'Salesforce developer',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [{ title: 'Salesforce developer', network: 'linkedin', username: 'https://www.linkedin.com/in/riddhi-siddhpura-b6817a199', is_primary: true, url: 'https://www.linkedin.com/in/riddhi-siddhpura-b6817a199' }],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Mumbai',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Certifications: Salesforce Certified Associate' }, company: { name: '' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/riddhi-siddhpura-b6817a199',
    job_title: 'Certifications: Salesforce Certified Associate',
    unique_key_string: 'riddhisiddhpura',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/riddhi-siddhpura-b6817a199' },
    std_function: 'unclassified',
    std_grade: 'entry',
    std_function_root: '',
  },
  {
    names: { first_name: 'Smit', last_name: 'Bhatt', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Smit',
    last_name: 'Bhatt',
    middle_name: null,
    middle_initial: null,
    full_name: 'Smit Bhatt',
    job_company_name: 'Deloitte USI',
    job_company_id: null,
    location_name: 'Mumbai',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/smit-bhatt-5bb990199',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'Salesforce Developer at Deloitte USI',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [{ title: 'Salesforce Developer at Deloitte USI', network: 'linkedin', username: 'https://www.linkedin.com/in/smit-bhatt-5bb990199', is_primary: true, url: 'https://www.linkedin.com/in/smit-bhatt-5bb990199' }],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Mumbai',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Analyst' }, company: { name: 'Deloitte USI' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/smit-bhatt-5bb990199',
    job_title: 'Analyst',
    unique_key_string: 'smitbhattdeloitteusi',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/smit-bhatt-5bb990199' },
    std_function: 'unclassified',
    std_grade: 'entry',
    std_function_root: '',
  },
  {
    names: { first_name: 'Palak', last_name: 'Handoo', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Palak',
    last_name: 'Handoo',
    middle_name: null,
    middle_initial: null,
    full_name: 'Palak Handoo',
    job_company_name: 'Accenture',
    job_company_id: null,
    location_name: 'Pune',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/palak-handoo-1b99b317b',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'Salesforce Developer at Accenture',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [{ title: 'Salesforce Developer at Accenture', network: 'linkedin', username: 'https://www.linkedin.com/in/palak-handoo-1b99b317b', is_primary: true, url: 'https://www.linkedin.com/in/palak-handoo-1b99b317b' }],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Pune',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Certifications: Salesforce Certified Platform Developer I' }, company: { name: 'Accenture' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/palak-handoo-1b99b317b',
    job_title: 'Certifications: Salesforce Certified Platform Developer I',
    unique_key_string: 'palakhandooaccenture',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/palak-handoo-1b99b317b' },
    std_function: 'software',
    std_grade: 'entry',
    std_function_root: 'technology',
  },
  {
    names: { first_name: 'Shubham', last_name: 'Loya', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Shubham',
    last_name: 'Loya',
    middle_name: null,
    middle_initial: null,
    full_name: 'Shubham Loya',
    job_company_name: '',
    job_company_id: null,
    location_name: 'Mumbai',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/shubham-kailas-loya',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'Salesforce System Engineer',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [{ title: 'Salesforce System Engineer', network: 'linkedin', username: 'https://www.linkedin.com/in/shubham-kailas-loya', is_primary: true, url: 'https://www.linkedin.com/in/shubham-kailas-loya' }],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Mumbai',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Salesforce System Engineer' }, company: { name: '' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/shubham-kailas-loya',
    job_title: 'Salesforce System Engineer',
    unique_key_string: 'shubhamloya',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/shubham-kailas-loya' },
    std_function: 'engineer system',
    std_grade: 'entry',
    std_function_root: 'engineering',
  },
  {
    names: { first_name: 'Sushant', last_name: 'Patil', title: null, middle_name: null, middle_initial: null, name: null, is_primary: null },
    id: null,
    first_name: 'Sushant',
    last_name: 'Patil',
    middle_name: null,
    middle_initial: null,
    full_name: 'Sushant Patil',
    job_company_name: 'Salesforce | Ex-LTIMindtree | Apex | LWC | Aura',
    job_company_id: null,
    location_name: 'Pune',
    job_company_linkedin_url: null,
    job_company_website: null,
    location_region: null,
    location_locality: null,
    location_metro: null,
    linkedin_url: 'https://www.linkedin.com/in/sushant-patil-09a50818b',
    facebook_url: null,
    twitter_url: null,
    location_country: null,
    profile_title: 'Technical Consultant at Salesforce | Ex-LTIMindtree | Apex | LWC | Aura',
    inferred_salary: null,
    inferred_years_experience: null,
    industry: null,
    country: null,
    birth_date_fuzzy: null,
    birth_date: null,
    gender: null,
    email_address: [],
    emails: { work: [], personal: [], others: [] },
    industries: [{ name: null, is_primary: null }],
    profiles: [
      {
        title: 'Technical Consultant at Salesforce | Ex-LTIMindtree | Apex | LWC | Aura',
        network: 'linkedin',
        username: 'https://www.linkedin.com/in/sushant-patil-09a50818b',
        is_primary: true,
        url: 'https://www.linkedin.com/in/sushant-patil-09a50818b',
      },
    ],
    phone_numbers: [],
    job_process: {
      applications: [{ job_ids: 'local_test_17_07', job_name: 'local_test_17_07', user_id: '64b29dbdf9822851831e4de8', current_status: 'sourced', timestamp: '2024-07-17 15:20:36', job_board: 'linkedin_premium', job_application_date: null }],
    },
    locations: [
      {
        name: 'Pune',
        locality: null,
        region: null,
        subregion: null,
        country: null,
        continent: null,
        type: null,
        geo: null,
        postal_code: null,
        zip_plus_4: null,
        street_address: null,
        address_line_2: null,
        most_recent: null,
        is_primary: true,
        last_updated: null,
      },
      { preferred_location: null },
    ],
    experience: [{ title: { name: 'Technical Consultant' }, company: { name: 'Salesforce | Ex-LTIMindtree | Apex | LWC | Aura' } }],
    experience_stats: { total_years_experience: { years: null, months: null }, current_salary: { type: null, ctc: null } },
    last_seen: { source: null, timestamp: null },
    last_updated: '2024-07-17 15:20:36',
    education: [{ institute: { name: null, type: null, location: null, profiles: [], website: null }, end_date: null, start_date: null, gpa: null, degrees: null, majors: [], minors: [], locations: null }],
    interests: [],
    skills: null,
    std_last_updated: null,
    created: 1721209836,
    creation_source: 'linkedin_premium',
    data_sources: ['linkedin_premium'],
    queryId: [],
    job_name: 'local_test_17_07',
    data_source: 'linkedin_premium',
    upload_count: 0,
    upload_id: '2b5fd90b634047c2a985982da2c86402',
    profile_url: 'https://www.linkedin.com/in/sushant-patil-09a50818b',
    job_title: 'Technical Consultant',
    unique_key_string: 'sushantpatilsalesforce|exltimindtree|apex|lwc|aura',
    tables: ['local_test_17_07'],
    socialprofiles: { linkedin: 'https://www.linkedin.com/in/sushant-patil-09a50818b' },
    std_function: 'technology',
    std_grade: 'entry',
    std_function_root: 'technology',
  },
];

export const job = {
  user_id: '64b29dbdf9822851831e4de8',
  job_id: 'newjobagain',
  job_name: 'newjobagain',
  job_company_name: 'newjobagain',
  job_company_id: 'newjobagain',
  sublists: [{ sublist_name: 'newjobagain', sublist_id: 'newjobagain', created_date: '2024-07-17 17:22:25' }],
  start_date: '2024-07-17 17:22:25',
  status: 'active',
  hot_columns: [
    { type: 'text', data: 'Remarks', width: 110, title: 'Remarks', id: 1 },
    { type: 'text', data: 'full_name', width: 110, title: 'Name', id: 2 },
    { type: 'text', data: 'job_company_name', width: 110, title: 'Company', id: 3 },
    { type: 'text', data: 'job_title', width: 180, title: 'Job Title', id: 4 },
    { type: 'text', data: 'std_function', width: 90, title: 'Function', id: 5, className: 'htCenter' },
    { type: 'text', data: 'std_grade', width: 75, title: 'Grade', id: 6, className: 'htCenter' },
    { type: 'text', data: 'profile_url', width: 80, title: 'Profile URL', id: 7, renderer: 'html', className: 'htCenter' },
    { type: 'dropdown', data: 'current_status', title: 'Status', source: ['Sourced', 'Enriched', 'Contacted', 'Disinterested', 'Interested', 'On Hold', 'CV Sent', 'Client Interview', 'Joined'], width: 120, id: 8, className: 'htCenter' },
    { type: 'text', data: 'std_function_root', width: 100, title: 'Func Root', id: 9, className: 'htCenter' },
    { type: 'text', data: 'profile_title', width: 200, title: 'Profile Intro', id: 10 },
    { type: 'text', data: 'skills', width: 250, title: 'Skills', id: 11 },
    { type: 'text', title: 'Education Institute Ug', data: 'education_institute_ug', width: 110, id: 12 },
    { type: 'text', title: 'Education Institute Pg', data: 'education_institute_pg', width: 110, id: 13 },
    { type: 'text', data: 'phone_numbers', width: 110, title: 'Mobile Phone', id: 14 },
    { type: 'text', data: 'email_address', width: 100, title: 'E-mail Address', id: 15 },
    { type: 'numeric', data: 'inferred_salary', width: 70, title: 'Salary', id: 16, className: 'htCenter' },
    { type: 'numeric', data: 'inferred_years_experience', width: 70, title: 'Experience', id: 17, className: 'htCenter' },
    { type: 'numeric', data: 'priority', width: 50, title: 'Priority', id: 18, className: 'htCenter' },
    { type: 'text', data: 'location_name', width: 90, title: 'Location', id: 19 },
    { type: 'text', data: 'std_location', width: 100, title: 'Std. Location', id: 20 },
    { type: 'text', data: 'notice_period', width: 90, title: 'Notice Period', id: 21 },
    { type: 'text', data: 'resume_link', width: 80, title: 'Resume URL', id: 22, renderer: 'html', className: 'htCenter' },
    { type: 'text', data: 'naukri_search_url', width: 80, title: 'Naukri Search URL', id: 23, renderer: 'html', className: 'htCenter' },
    { type: 'numeric', data: 'distance_from_location', width: 60, title: 'Distance from Location', id: 24 },
    { type: 'numeric', data: 'distance_from_job', width: 60, title: 'Distance from Job', id: 25 },
    { type: 'text', data: 'job_company_id', width: 60, title: 'Org Chart', id: 26 },
    { type: 'text', data: 'std_company_name', width: 60, title: 'Company Name', id: 27 },
    { type: 'numeric', data: 'current_role_tenure', width: 60, title: 'Current Role Tenure', id: 28 },
    { type: 'numeric', data: 'total_tenure', width: 60, title: 'Total Tenure', id: 29 },
    { type: 'numeric', data: 'total_job_changes', width: 60, title: 'Total Job Changes', id: 28 },
    { type: 'numeric', data: 'average_tenure', width: 60, title: 'Average Tenure', id: 30 },
    { type: 'numeric', data: 'count_promotions', width: 60, title: 'Count Promotions', id: 31 },
    { type: 'numeric', data: 'job_company_linkedin_url', width: 60, title: 'Employees in Function', id: 32, renderer: 'html' },
    { type: 'numeric', data: 'count_org', width: 60, title: 'Employees in Company', id: 33 },
    { type: 'numeric', data: 'employees_at_location', width: 60, title: 'Employees at Location', id: 34 },
    { type: 'numeric', data: 'current_salary', width: 60, title: 'Salary', id: 35, className: 'htCenter' },
    { type: 'numeric', data: 'years_of_experience', width: 60, title: 'Experience', id: 36, className: 'htCenter' },
    { type: 'text', data: 'industry', width: 60, title: 'Industry', id: 37 },
    { type: 'text', data: 'nationality', width: 60, title: 'Nationality', id: 38 },
    { type: 'text', data: 'year_of_passing', width: 60, title: 'Year Of Passing', id: 39 },
    { type: 'text', data: 'blank_3', width: 60, title: 'Blank_3', id: 40 },
    { type: 'numeric', data: 'data_source', width: 60, title: 'Source', id: 41 },
    { type: 'numeric', data: 'upload_count', width: 50, title: 'Pull ID', id: 42, className: 'htCenter' },
    { type: 'text', data: 'last_updated', width: 115, title: 'Last Updated', readOnly: 1, editor: 0, id: 43 },
    { type: 'text', data: 'first_name', width: 60, title: 'First Name', id: 44 },
    { type: 'text', data: 'last_name', width: 60, title: 'Last Name', id: 45 },
    { type: 'text', data: 'job_name', width: 80, title: 'Job', id: 46, readOnly: 1, editor: 0, className: 'htCenter' },
    { type: 'text', data: '_id', width: 60, title: 'ID', readOnly: 1, editor: 0, id: 47 },
    { type: 'text', data: 'unique_key_string', width: 60, title: 'unique_key_string', readOnly: 1, editor: 0, id: 48 },
  ],
  statuses: [
    { status_name: 'Sourced', status_value: 'sourced', progress_value: 1 },
    { status_name: 'Enriched', status_value: 'enriched', progress_value: 2 },
    { status_name: 'Contacted', status_value: 'contacted', progress_value: 3 },
    { status_name: 'Disinterested', status_value: 'disinterested', progress_value: 4 },
    { status_name: 'Interested', status_value: 'interested', progress_value: 5 },
    { status_name: 'On Hold', status_value: 'on_hold_by_recruiter', progress_value: 6 },
    { status_name: 'CV Sent', status_value: 'on_hold_by_recruiter', progress_value: 7 },
    { status_name: 'Client Interview', status_value: 'client_interview', progress_value: 8 },
    { status_name: 'Joined', status_value: 'joined', progress_value: 9 },
  ],
};

export const arxenaColumns = [
  'Remarks',
  'Name',
  'Company',
  'Job Title',
  'Function',
  'Grade',
  'Profile URL',
  'Status',
  'Func Root',
  'Profile Intro',
  'Skills',
  'Education Institute Ug',
  'Education Institute Pg',
  'Mobile Phone',
  'E-mail Address',
  'Salary',
  'Experience',
  'Priority',
  'Location',
  'Std. Location',
  'Notice Period',
  'Resume URL',
  'Naukri Search URL',
  'Distance from Location',
  'Distance from Job',
  'Org Chart',
  'Company Name',
  'Current Role Tenure',
  'Total Tenure',
  'Total Job Changes',
  'Average Tenure',
  'Count Promotions',
  'Employees in Function',
  'Employees in Company',
  'Employees at Location',
  'Salary',
  'Experience',
  'Industry',
  'Nationality',
  'Year Of Passing',
  'Blank_3',
  'Source',
  'Pull ID',
  'Last Updated',
  'First Name',
  'Last Name',
  'Job',
  'ID',
];

var display_objs = {
  company_name: 'Company Name',
  gpt3_company_search: 'GPT3 Company Search',
  company_id: 'Linkedin Company Id',
  person_name: 'Person Name',
  job_title: 'Job Title',
  reverse_job_title: 'Similar Job Titles',
  reverse_company: 'Preceding Companies',
  region: 'State/ Region',
  locality: 'City/ Locality',
  industry: 'Industry',
  industry_category: 'Industry Category',
  functions: 'Functions',
  function_root: 'Functional Area',
  grades: 'Seniority',
  skills: 'Skills',
  locations: 'Locations',
  country: 'Country',
  school: 'Schools',
  genders: 'Genders',
  person_linkedin_url: 'Person Linkedin URL',
  inferred_salary: 'Salary',
  company_sizes: 'Company Sizes',
  education_degrees: 'Degrees',
  education_majors: 'Majors',
  email_address: 'Email',
  phone_number: 'Phone',
  year_of_graduation: 'Year of Graduation',
};

export const arxenaColumnsV2 = [
  'id',
  'first_name',
  'last_name',
  'middle_name',
  'middle_initial',
  'full_name',
  'job_company_name',
  'job_company_id',
  'location_name',
  'job_company_linkedin_url',
  'job_company_website',
  'location_region',
  'location_locality',
  'location_metro',
  'linkedin_url',
  'facebook_url',
  'twitter_url',
  'location_country',
  'profile_title',
  'inferred_salary',
  'inferred_years_experience',
  'industry',
  'country',
  'birth_date_fuzzy',
  'birth_date',
  'gender',
  'last_updated',
  'skills',
  'std_last_updated',
  'created',
  'creation_source',
  'job_name',
  'data_source',
  'upload_count',
  'upload_id',
  'profile_url',
  'job_title',
  'unique_key_string',
  'std_function',
  'std_grade',
  'std_function_root',
];
