import { Injectable, Logger } from '@nestjs/common';
import OpenAI from 'openai';
import { zodResponseFormat } from 'openai/helpers/zod';
import {
  LinkedInClassicPeopleSearchRequest,
  LinkedInRecruiterPeopleSearchRequest,
  LinkedInSalesNavigatorPeopleSearchRequest,
} from '../../linkedin-search/types/linkedin-search-request.type';
import { SearchParametersPrompts } from '../prompts/search-parameters-prompts';
import { QueryUnderstanding, searchStrategyTextSchema } from '../schemas/query-understanding.schema';
import {
  ClassicPeopleSearchStrategyResult, RecruiterPeopleSearchStrategyResult,
  SalesNavigatorPeopleSearchStrategyResult
} from '../types/candidate-search-request.type';
import { TokenUsage } from '../utils/token-tracking.util';
import { StreamProcessingService } from './stream-processing.service';

@Injectable()
export class SearchStrategyService {
  private readonly logger = new Logger(SearchStrategyService.name);

  constructor(
    private readonly searchParametersPrompts: SearchParametersPrompts,
    private readonly streamProcessingService: StreamProcessingService,
  ) {}

  /**
   * Format QueryUnderstanding as natural language text for passing between LLM calls
   */
  formatQueryUnderstandingAsText(queryUnderstanding: QueryUnderstanding, userMessage: string): string {
    const parts: string[] = [];

    parts.push(`ORIGINAL USER QUERY: "${userMessage}"`);
    parts.push('');

    parts.push('QUERY UNDERSTANDING (Generated by LLM):');
    parts.push(`Primary Role: ${queryUnderstanding.primaryRole}`);
    
    if (queryUnderstanding.roleVariations.length > 0) {
      parts.push(`Role Variations: ${queryUnderstanding.roleVariations.join(', ')} (${queryUnderstanding.roleVariations.length} variations)`);
    }

    if (queryUnderstanding.industry && queryUnderstanding.industry.length > 0) {
      parts.push(`Industry: ${queryUnderstanding.industry.join(', ')} (${queryUnderstanding.industry.length} industries)`);
    } else {
      parts.push('Industry: Not specified');
    }

    parts.push('Location Hierarchy:');
    parts.push(`  - Primary: ${queryUnderstanding.locationHierarchy.primary || 'Not specified'}`);
    if (queryUnderstanding.locationHierarchy.secondary && queryUnderstanding.locationHierarchy.secondary.length > 0) {
      parts.push(`  - Secondary: ${queryUnderstanding.locationHierarchy.secondary.join(', ')} (${queryUnderstanding.locationHierarchy.secondary.length} locations)`);
    }
    if (queryUnderstanding.locationHierarchy.regional) {
      parts.push(`  - Regional: ${queryUnderstanding.locationHierarchy.regional}`);
    }

    if (queryUnderstanding.companyPreferences) {
      parts.push('Company Preferences:');
      if (queryUnderstanding.companyPreferences.current && queryUnderstanding.companyPreferences.current.length > 0) {
        parts.push(`  - Current: ${queryUnderstanding.companyPreferences.current.join(', ')} (${queryUnderstanding.companyPreferences.current.length} companies)`);
      }
      if (queryUnderstanding.companyPreferences.past && queryUnderstanding.companyPreferences.past.length > 0) {
        parts.push(`  - Past: ${queryUnderstanding.companyPreferences.past.join(', ')} (${queryUnderstanding.companyPreferences.past.length} companies)`);
      }
      if (queryUnderstanding.companyPreferences.types && queryUnderstanding.companyPreferences.types.length > 0) {
        parts.push(`  - Types: ${queryUnderstanding.companyPreferences.types.join(', ')}`);
      }
    }

    if (queryUnderstanding.hierarchicalLevel) {
      parts.push(`Hierarchical Level: ${queryUnderstanding.hierarchicalLevel}`);
    }
    if (queryUnderstanding.subHierarchicalLevel) {
      parts.push(`Sub-Hierarchical Level: ${queryUnderstanding.subHierarchicalLevel}`);
    }

    if (queryUnderstanding.functionalRole) {
      parts.push(`Functional Role: ${queryUnderstanding.functionalRole}`);
    }
    if (queryUnderstanding.subFunctionalRole) {
      parts.push(`Sub-Functional Role: ${queryUnderstanding.subFunctionalRole}`);
    }

    if (queryUnderstanding.domainContext) {
      parts.push(`Domain Context: ${queryUnderstanding.domainContext}`);
    }

    if (queryUnderstanding.skills && queryUnderstanding.skills.length > 0) {
      parts.push(`Skills: ${queryUnderstanding.skills.join(', ')}`);
    }

    if (queryUnderstanding.experienceRequirements) {
      parts.push(`Experience Requirements: ${queryUnderstanding.experienceRequirements}`);
    }

    if (queryUnderstanding.explicitRequirements.length > 0) {
      parts.push(`Explicit Requirements: ${queryUnderstanding.explicitRequirements.join(', ')}`);
    }

    if (queryUnderstanding.preferredRequirements.length > 0) {
      parts.push(`Preferred Requirements: ${queryUnderstanding.preferredRequirements.join(', ')}`);
    }

    if (queryUnderstanding.certifications && queryUnderstanding.certifications.length > 0) {
      const requiredCerts = queryUnderstanding.certifications.filter(c => c.required).map(c => c.name);
      const preferredCerts = queryUnderstanding.certifications.filter(c => !c.required).map(c => c.name);
      if (requiredCerts.length > 0) {
        parts.push(`Required Certifications: ${requiredCerts.join(', ')}`);
      }
      if (preferredCerts.length > 0) {
        parts.push(`Preferred Certifications: ${preferredCerts.join(', ')}`);
      }
    }

    if (queryUnderstanding.regulatoryExperience && queryUnderstanding.regulatoryExperience.length > 0) {
      parts.push(`Regulatory Experience: ${queryUnderstanding.regulatoryExperience.join(', ')}`);
    }

    if (queryUnderstanding.companyGroupPreferences && queryUnderstanding.companyGroupPreferences.length > 0) {
      parts.push(`Company Groups: ${queryUnderstanding.companyGroupPreferences.join(', ')}`);
    }

    if (queryUnderstanding.needsClarification) {
      parts.push(`Needs Clarification: Yes`);
      if (queryUnderstanding.clarificationQuestions && queryUnderstanding.clarificationQuestions.length > 0) {
        parts.push(`Clarification Questions: ${queryUnderstanding.clarificationQuestions.join('; ')}`);
      }
    }
    if (queryUnderstanding.clarificationAnswers) {
      parts.push(`Clarification Answers: (User provided) ${queryUnderstanding.clarificationAnswers}`);
    }
    if (queryUnderstanding.companyTypeSignals) {
      parts.push('Company Type Signals: (Generated by LLM)');
      if (queryUnderstanding.companyTypeSignals.industryKeywords && queryUnderstanding.companyTypeSignals.industryKeywords.length > 0) {
        parts.push(`  - Industry Keywords: ${queryUnderstanding.companyTypeSignals.industryKeywords.join(', ')}`);
      }
      if (queryUnderstanding.companyTypeSignals.productKeywords && queryUnderstanding.companyTypeSignals.productKeywords.length > 0) {
        parts.push(`  - Product Keywords: ${queryUnderstanding.companyTypeSignals.productKeywords.join(', ')}`);
      }
      if (queryUnderstanding.companyTypeSignals.businessModelKeywords && queryUnderstanding.companyTypeSignals.businessModelKeywords.length > 0) {
        parts.push(`  - Business Model Keywords: ${queryUnderstanding.companyTypeSignals.businessModelKeywords.join(', ')}`);
      }
      if (queryUnderstanding.companyTypeSignals.companyTypeDescription) {
        parts.push(`  - Company Type: ${queryUnderstanding.companyTypeSignals.companyTypeDescription}`);
      }
    }
    return parts.join('\n');
  }

  /**
   * Generate search strategies as natural language text descriptions
   * Uses LLM to generate strategy descriptions based on query understanding and complexity
   */


   /**
   * Generate example boolean queries for strategy generation
   */

  //     private async getAvailableParameters(searchType: 'classic' | 'sales_navigator' | 'recruiter'): Promise<string> {
  //   if (searchType === 'classic') {
  //     return `Available parameters for Classic LinkedIn Search:
  // - keywords: Job titles, role names, or search terms (required)
  // - location: Geographic locations (city, state, country)
  // - industry: Industry sectors
  // - company: Current company names
  // - past_company: Past company names
  // - school: Educational institutions
  // - profile_language: Profile language
  // - network_distance: Connection degree (1st, 2nd, 3rd)
  // - service: Service categories
  // - connections_of: Connections of specific people
  // - followers_of: Followers of specific entities
  // - open_to: Open to opportunities
  // - advanced_keywords: Advanced keyword filters (first_name, last_name, title, company, school)`;
  //   } else if (searchType === 'sales_navigator') {
  //     return `Available parameters for Sales Navigator Search:
  // - keywords: Job titles, role names, or search terms (required)
  // - location: Geographic locations (include/exclude)
  // - industry: Industry sectors (include/exclude)
  // - company: Current company names (include/exclude)
  // - past_company: Past company names (include/exclude)
  // - role: Job roles (include/exclude)
  // - function: Job functions (include/exclude)
  // - seniority: Seniority levels
  // - school: Educational institutions (include/exclude)`;
  //   } else {
  //     return `Available parameters for Recruiter Search:
  // - keywords: Job titles, role names, or search terms (required)
  // - location: Geographic locations (include/exclude)
  // - industry: Industry sectors (include/exclude)
  // - company: Current company names (include/exclude)
  // - past_company: Past company names (include/exclude)
  // - role: Job roles (include/exclude)
  // - seniority: Seniority levels
  // - skills: Skills and competencies (include/exclude)
  // - school: Educational institutions (include/exclude)`;
  //   }
  // }


  
  async generateStrategies(
    openaiClient: OpenAI,
    queryUnderstandingText: string,
    userMessage: string,
    searchType: 'classic' | 'sales_navigator' | 'recruiter',
    queryUnderstanding: QueryUnderstanding,
    sendEvent?: (event: string, data: any) => boolean | void,
    model: string = 'gpt-5.1-chat-latest',
    onTokenUsage?: (usage: TokenUsage) => void,
  ): Promise<Array<{ strategyText: string; label?: string; }>> {
    this.logger.log(`Generating search strategies for model with query understanding: ${queryUnderstandingText} and user message: ${userMessage} and model: ${model}`);
    const isStreamAborted = sendEvent?.('status', { message: 'Generating search strategies...' });
    if (isStreamAborted === false) {
      this.logger.log('Stream aborted during strategy generation');
      // Return default strategy on abort
      return [{
        strategyText: `Use keywords (job titles) and location and industry`,
        label: 'Default Strategy',
      }];
    }


    const strategyGenerationPrompt = await this.searchParametersPrompts.getStrategyGenerationPrompt(
      queryUnderstandingText,
      userMessage,
      searchType,
    );



    const strategyGenerationSystemPrompt = await this.searchParametersPrompts.getStrategyGenerationSystemPrompt(
      searchType,
    );


    const strategyGenerationStream = await this.streamProcessingService.createStreamingCompletion(
      openaiClient,
      [
        { role: 'system' as const, content: strategyGenerationSystemPrompt },
        { role: 'user' as const, content: strategyGenerationPrompt },
      ],
      zodResponseFormat(searchStrategyTextSchema, 'searchStrategyText'),
      model,
    );

    const strategyGenerationResult = await this.streamProcessingService.processStreamChunks(strategyGenerationStream, sendEvent);
    const strategyGenerationResponse = typeof strategyGenerationResult === 'string' 
      ? strategyGenerationResult 
      : strategyGenerationResult.content;
    
    // Accumulate token usage if available
    if (typeof strategyGenerationResult !== 'string' && strategyGenerationResult.usage && onTokenUsage) {
      onTokenUsage(strategyGenerationResult.usage);
    }

    if (!strategyGenerationResponse) {
      this.logger.warn('Strategy generation returned empty content. Using default strategy.');
      return [{
        strategyText: `Use keywords (job titles) and location and industry`,
        label: 'Default Strategy',
      }];
    }

    try {
      const parsedStrategyGeneration = JSON.parse(strategyGenerationResponse);
      const validated = searchStrategyTextSchema.parse(parsedStrategyGeneration);
      this.logger.log(`Generated ${validated.strategies.length} search strategies`);
      
      return validated.strategies.map(s => ({
        strategyText: s.strategyText,
        label: s.label || undefined,
      }));
    } catch (error) {
      this.logger.error(`Failed to parse strategy generation: ${error}`);
      // Return default strategy on error
      return [{
        strategyText: `Use keywords (job titles) and location and industry`,
        label: 'Default Strategy',
      }];
    }
  }


  buildStrategyResult(
    parameters: Omit<LinkedInClassicPeopleSearchRequest, 'api' | 'category'> | 
                 Omit<LinkedInSalesNavigatorPeopleSearchRequest, 'api' | 'category'> | 
                 Omit<LinkedInRecruiterPeopleSearchRequest, 'api' | 'category'>,
    searchType: 'classic' | 'sales_navigator' | 'recruiter',
    strategyDef: {
      id: string;
      label: string;
      description: string; // Can contain strategy text or modified description
      strategyText: string; // Original strategy text from generateStrategies - serves as guideline
      originalUserQuery?: string; // Original user query that led to this strategy - for traceability
      clarificationQuestions?: string[] | null; // Clarification questions asked (if any) - for traceability
      clarificationAnswers?: string | null; // User's answers to clarification questions (if any) - for traceability
    },
  ): ClassicPeopleSearchStrategyResult | SalesNavigatorPeopleSearchStrategyResult | RecruiterPeopleSearchStrategyResult {
    if (searchType === 'classic') {
      return {
        ...strategyDef,
        parameters: parameters as Omit<LinkedInClassicPeopleSearchRequest, 'api' | 'category'>,
      } as ClassicPeopleSearchStrategyResult;
    } else if (searchType === 'sales_navigator') {
      return {
        ...strategyDef,
        parameters: parameters as Omit<LinkedInSalesNavigatorPeopleSearchRequest, 'api' | 'category'>,
      } as SalesNavigatorPeopleSearchStrategyResult;
    } else {
      return {
        ...strategyDef,
        parameters: parameters as Omit<LinkedInRecruiterPeopleSearchRequest, 'api' | 'category'>,
      } as RecruiterPeopleSearchStrategyResult;
    }
  }
}

