export enum CacheStorageNamespace {
  ModuleApplications = 'module:applications',
  ModuleMessaging = 'module:messaging',
  ModuleEmailing = 'module:emailing',
  ModuleCalendar = 'module:calendar',
  ModuleWorkflow = 'module:workflow',
  EngineWorkspace = 'engine:workspace',
  EngineCoreEntity = 'engine:core-entity',
  EngineLock = 'engine:lock',
  EngineHealth = 'engine:health',
  EngineMetrics = 'engine:metrics',
  EngineSubscriptions = 'engine:subscriptions',
  EngineBillingUsage = 'engine:billing-usage',
  EngineOnboardingInviteSuggestions = 'engine:onboarding-invite-suggestions',
  EngineApify = 'engine:apify',
  EngineOrgChart = 'engine:org-chart',
  EngineCandidateSearch = 'engine:candidate-search',
  EngineContactEnrichment = 'engine:contact-enrichment',
  EngineTheOrg = 'engine:theorg',
  IntegrationTests = 'integration-tests',
}
