/*
 *     _
 *    / \    _ __  __  __   ___   _ __    __ _
 *   / _ \  | '__| \ \/ /  / _ \ | '_ \  / _` | Auto-generated file
 *  / ___ \ | |     >  <  |  __/ | | | || (_| | Any edits to this will be overridden
 * /_/   \_\|_|    /_/\_\  \___| |_| |_| \__,_| Generated by: npx nx version:bump twenty-server
 */

export const TWENTY_CURRENT_VERSION = '2.25.0' as const;
