import { RightDrawerPages } from '@/ui/layout/right-drawer/types/RightDrawerPages';

export const RIGHT_DRAWER_PAGE_TITLES = {
  [RightDrawerPages.ViewEmailThread]: 'Email Thread',
  [RightDrawerPages.ViewCalendarEvent]: 'Calendar Event',
  [RightDrawerPages.ViewRecord]: 'Record Editor',
  [RightDrawerPages.Copilot]: 'Copilot',
  [RightDrawerPages.ClientChat]: 'Client Chat',
  [RightDrawerPages.WorkflowStepSelectTriggerType]: 'Workflow',
  [RightDrawerPages.WorkflowStepSelectAction]: 'Workflow',
  [RightDrawerPages.WorkflowStepEdit]: 'Workflow',
  [RightDrawerPages.WorkflowStepView]: 'Workflow',
  [RightDrawerPages.SimpleActivity]: 'Activity',
  [RightDrawerPages.AllActions]: 'All Actions',
  [RightDrawerPages.CandidateActions]: 'Candidate Actions',
  [RightDrawerPages.Notifications]: 'Notifications',
  [RightDrawerPages.CandidateChat]: 'Candidate Info',
  // [RightDrawerPages.CandidateInfo]: 'Candidate Info',
  // [RightDrawerPages.CandidateProfile]: 'Candidate Profile',
  // [RightDrawerPages.CandidateCV]: 'Candidate CV',
  // [RightDrawerPages.CandidateVideoInterview]: 'Candidate Video Interview',
  // [RightDrawerPages.CandidateChat]: 'Candidate Chat',
  // [RightDrawerPages.CandidateInfo]: 'Candidate Info',
  // [RightDrawerPages.CandidateProfile]: 'Candidate Profile',
  // [RightDrawerPages.CandidateCV]: 'Candidate CV',
  // [RightDrawerPages.CandidateVideoInterview]: 'Candidate Video Interview',
};
