import { type UploadProfilesPerson } from 'src/engine/core-modules/outreach-command/utils/normalize-upload-people.util';
import {
  buildOutreachMockUnipileUploadPeople,
  OUTREACH_MOCK_UNIPILE_RAW_PROFILES,
} from 'src/engine/core-modules/outreach-command/utils/outreach-mock-unipile-profiles.util';

export const OUTREACH_MOCK_UPLOAD_DEFAULT_COUNT = 5;

type OutreachMockExecutive = {
  firstName: string;
  lastName: string;
  title: string;
  company: string;
  location: string;
  linkedinSlug: string;
};

// Real MD / CEO personas — one company each so maxPersonasPerCompany does not
// collapse the batch. Stamp + index uniquifies linkedinProfileId for uploads.
export const OUTREACH_MOCK_MD_CEO_PROFILES: OutreachMockExecutive[] = [
  {
    firstName: 'Satya',
    lastName: 'Nadella',
    title: 'CEO',
    company: 'Microsoft',
    location: 'Redmond, Washington, United States',
    linkedinSlug: 'satyanadella',
  },
  {
    firstName: 'Tim',
    lastName: 'Cook',
    title: 'CEO',
    company: 'Apple',
    location: 'Cupertino, California, United States',
    linkedinSlug: 'tim-cook-1',
  },
  {
    firstName: 'Sundar',
    lastName: 'Pichai',
    title: 'CEO',
    company: 'Alphabet',
    location: 'Mountain View, California, United States',
    linkedinSlug: 'sundarpichai',
  },
  {
    firstName: 'Jensen',
    lastName: 'Huang',
    title: 'CEO',
    company: 'NVIDIA',
    location: 'Santa Clara, California, United States',
    linkedinSlug: 'jenhsunhuang',
  },
  {
    firstName: 'Andy',
    lastName: 'Jassy',
    title: 'CEO',
    company: 'Amazon',
    location: 'Seattle, Washington, United States',
    linkedinSlug: 'andy-jassy-8b8335b',
  },
  {
    firstName: 'Mark',
    lastName: 'Zuckerberg',
    title: 'CEO',
    company: 'Meta',
    location: 'Menlo Park, California, United States',
    linkedinSlug: 'markzuckerberg',
  },
  {
    firstName: 'Arvind',
    lastName: 'Krishna',
    title: 'CEO',
    company: 'IBM',
    location: 'Armonk, New York, United States',
    linkedinSlug: 'arvindkrishna',
  },
  {
    firstName: 'Shantanu',
    lastName: 'Narayen',
    title: 'CEO',
    company: 'Adobe',
    location: 'San Jose, California, United States',
    linkedinSlug: 'shantanu-narayen',
  },
  {
    firstName: 'Lisa',
    lastName: 'Su',
    title: 'CEO',
    company: 'AMD',
    location: 'Santa Clara, California, United States',
    linkedinSlug: 'lisa-su',
  },
  {
    firstName: 'Patrick',
    lastName: 'Collison',
    title: 'CEO',
    company: 'Stripe',
    location: 'San Francisco, California, United States',
    linkedinSlug: 'patrickcollison',
  },
  {
    firstName: 'Brian',
    lastName: 'Armstrong',
    title: 'CEO',
    company: 'Coinbase',
    location: 'San Francisco, California, United States',
    linkedinSlug: 'barmstrong',
  },
  {
    firstName: 'Brian',
    lastName: 'Chesky',
    title: 'CEO',
    company: 'Airbnb',
    location: 'San Francisco, California, United States',
    linkedinSlug: 'brianchesky',
  },
  {
    firstName: 'Dara',
    lastName: 'Khosrowshahi',
    title: 'CEO',
    company: 'Uber',
    location: 'San Francisco, California, United States',
    linkedinSlug: 'dkhosrowshahi',
  },
  {
    firstName: 'Daniel',
    lastName: 'Ek',
    title: 'CEO',
    company: 'Spotify',
    location: 'Stockholm, Sweden',
    linkedinSlug: 'daniel-ek-1',
  },
  {
    firstName: 'Tobias',
    lastName: 'Lütke',
    title: 'CEO',
    company: 'Shopify',
    location: 'Ottawa, Ontario, Canada',
    linkedinSlug: 'tobi',
  },
  {
    firstName: 'Dylan',
    lastName: 'Field',
    title: 'CEO',
    company: 'Figma',
    location: 'San Francisco, California, United States',
    linkedinSlug: 'dylanfield',
  },
  {
    firstName: 'Marc',
    lastName: 'Benioff',
    title: 'CEO',
    company: 'Salesforce',
    location: 'San Francisco, California, United States',
    linkedinSlug: 'marcbenioff',
  },
  {
    firstName: 'Chuck',
    lastName: 'Robbins',
    title: 'CEO',
    company: 'Cisco',
    location: 'San Jose, California, United States',
    linkedinSlug: 'chuckrobbins',
  },
  {
    firstName: 'Hock',
    lastName: 'Tan',
    title: 'CEO',
    company: 'Broadcom',
    location: 'San Jose, California, United States',
    linkedinSlug: 'hock-tan',
  },
  {
    firstName: 'Cristiano',
    lastName: 'Amon',
    title: 'CEO',
    company: 'Qualcomm',
    location: 'San Diego, California, United States',
    linkedinSlug: 'cristianoamon',
  },
  {
    firstName: 'Lip-Bu',
    lastName: 'Tan',
    title: 'CEO',
    company: 'Intel',
    location: 'Santa Clara, California, United States',
    linkedinSlug: 'lip-bu-tan',
  },
  {
    firstName: 'Safra',
    lastName: 'Catz',
    title: 'CEO',
    company: 'Oracle',
    location: 'Austin, Texas, United States',
    linkedinSlug: 'safracatz',
  },
  {
    firstName: 'Christian',
    lastName: 'Klein',
    title: 'CEO',
    company: 'SAP',
    location: 'Walldorf, Germany',
    linkedinSlug: 'christian-klein-sap',
  },
  {
    firstName: 'Sam',
    lastName: 'Altman',
    title: 'CEO',
    company: 'OpenAI',
    location: 'San Francisco, California, United States',
    linkedinSlug: 'sama',
  },
  {
    firstName: 'Dario',
    lastName: 'Amodei',
    title: 'CEO',
    company: 'Anthropic',
    location: 'San Francisco, California, United States',
    linkedinSlug: 'dario-amodei',
  },
  {
    firstName: 'Demis',
    lastName: 'Hassabis',
    title: 'CEO',
    company: 'Google DeepMind',
    location: 'London, United Kingdom',
    linkedinSlug: 'demishassabis',
  },
  {
    firstName: 'Ted',
    lastName: 'Sarandos',
    title: 'Co-CEO',
    company: 'Netflix',
    location: 'Los Angeles, California, United States',
    linkedinSlug: 'tedsarandos',
  },
  {
    firstName: 'Elon',
    lastName: 'Musk',
    title: 'CEO',
    company: 'Tesla',
    location: 'Austin, Texas, United States',
    linkedinSlug: 'elonmusk',
  },
  {
    firstName: 'Gwynne',
    lastName: 'Shotwell',
    title: 'President and COO',
    company: 'SpaceX',
    location: 'Hawthorne, California, United States',
    linkedinSlug: 'gwynneshotwell',
  },
  {
    firstName: 'Bob',
    lastName: 'Iger',
    title: 'CEO',
    company: 'The Walt Disney Company',
    location: 'Burbank, California, United States',
    linkedinSlug: 'robertiger',
  },
  {
    firstName: 'David',
    lastName: 'Zaslav',
    title: 'CEO',
    company: 'Warner Bros. Discovery',
    location: 'New York, New York, United States',
    linkedinSlug: 'davidzaslav',
  },
  {
    firstName: 'Brian',
    lastName: 'Roberts',
    title: 'CEO',
    company: 'Comcast',
    location: 'Philadelphia, Pennsylvania, United States',
    linkedinSlug: 'brianlroberts',
  },
  {
    firstName: 'Neal',
    lastName: 'Mohan',
    title: 'CEO',
    company: 'YouTube',
    location: 'San Bruno, California, United States',
    linkedinSlug: 'neal-mohan',
  },
  {
    firstName: 'Shou',
    lastName: 'Zi Chew',
    title: 'CEO',
    company: 'TikTok',
    location: 'Singapore',
    linkedinSlug: 'shou-zi-chew',
  },
  {
    firstName: 'Evan',
    lastName: 'Spiegel',
    title: 'CEO',
    company: 'Snap Inc.',
    location: 'Santa Monica, California, United States',
    linkedinSlug: 'evanspiegel',
  },
  {
    firstName: 'Linda',
    lastName: 'Yaccarino',
    title: 'CEO',
    company: 'X',
    location: 'New York, New York, United States',
    linkedinSlug: 'lindayaccarino',
  },
  {
    firstName: 'Fidji',
    lastName: 'Simo',
    title: 'CEO',
    company: 'Instacart',
    location: 'San Francisco, California, United States',
    linkedinSlug: 'fidjisimo',
  },
  {
    firstName: 'Jamie',
    lastName: 'Dimon',
    title: 'CEO',
    company: 'JPMorgan Chase',
    location: 'New York, New York, United States',
    linkedinSlug: 'jamiedimon',
  },
  {
    firstName: 'Brian',
    lastName: 'Moynihan',
    title: 'CEO',
    company: 'Bank of America',
    location: 'Charlotte, North Carolina, United States',
    linkedinSlug: 'brianmoynihan',
  },
  {
    firstName: 'Jane',
    lastName: 'Fraser',
    title: 'CEO',
    company: 'Citigroup',
    location: 'New York, New York, United States',
    linkedinSlug: 'jane-fraser',
  },
  {
    firstName: 'David',
    lastName: 'Solomon',
    title: 'CEO',
    company: 'Goldman Sachs',
    location: 'New York, New York, United States',
    linkedinSlug: 'davidmsolomon',
  },
  {
    firstName: 'Ted',
    lastName: 'Pick',
    title: 'CEO',
    company: 'Morgan Stanley',
    location: 'New York, New York, United States',
    linkedinSlug: 'ted-pick',
  },
  {
    firstName: 'Larry',
    lastName: 'Fink',
    title: 'CEO',
    company: 'BlackRock',
    location: 'New York, New York, United States',
    linkedinSlug: 'larryfink',
  },
  {
    firstName: 'Stephen',
    lastName: 'Schwarzman',
    title: 'CEO',
    company: 'Blackstone',
    location: 'New York, New York, United States',
    linkedinSlug: 'stephen-schwarzman',
  },
  {
    firstName: 'Warren',
    lastName: 'Buffett',
    title: 'CEO',
    company: 'Berkshire Hathaway',
    location: 'Omaha, Nebraska, United States',
    linkedinSlug: 'warrenbuffett',
  },
  {
    firstName: 'Mary',
    lastName: 'Barra',
    title: 'CEO',
    company: 'General Motors',
    location: 'Detroit, Michigan, United States',
    linkedinSlug: 'marybarra',
  },
  {
    firstName: 'Jim',
    lastName: 'Farley',
    title: 'CEO',
    company: 'Ford Motor Company',
    location: 'Dearborn, Michigan, United States',
    linkedinSlug: 'jim-farley',
  },
  {
    firstName: 'Oliver',
    lastName: 'Blume',
    title: 'CEO',
    company: 'Volkswagen',
    location: 'Wolfsburg, Germany',
    linkedinSlug: 'oliver-blume',
  },
  {
    firstName: 'Ola',
    lastName: 'Källenius',
    title: 'CEO',
    company: 'Mercedes-Benz Group',
    location: 'Stuttgart, Germany',
    linkedinSlug: 'ola-kaellenius',
  },
  {
    firstName: 'Oliver',
    lastName: 'Zipse',
    title: 'CEO',
    company: 'BMW',
    location: 'Munich, Germany',
    linkedinSlug: 'oliver-zipse',
  },
  {
    firstName: 'Koji',
    lastName: 'Sato',
    title: 'CEO',
    company: 'Toyota',
    location: 'Toyota City, Japan',
    linkedinSlug: 'koji-sato-toyota',
  },
  {
    firstName: 'Makoto',
    lastName: 'Uchida',
    title: 'CEO',
    company: 'Nissan Motor',
    location: 'Yokohama, Japan',
    linkedinSlug: 'makoto-uchida',
  },
  {
    firstName: 'Toshihiro',
    lastName: 'Mibe',
    title: 'CEO',
    company: 'Honda Motor',
    location: 'Tokyo, Japan',
    linkedinSlug: 'toshihiro-mibe',
  },
  {
    firstName: 'Bernard',
    lastName: 'Arnault',
    title: 'CEO',
    company: 'LVMH',
    location: 'Paris, France',
    linkedinSlug: 'bernard-arnault',
  },
  {
    firstName: 'François-Henri',
    lastName: 'Pinault',
    title: 'CEO',
    company: 'Kering',
    location: 'Paris, France',
    linkedinSlug: 'francois-henri-pinault',
  },
  {
    firstName: 'Salil',
    lastName: 'Parekh',
    title: 'CEO',
    company: 'Infosys',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'salilsparekh',
  },
  {
    firstName: 'Srinivas',
    lastName: 'Pallia',
    title: 'CEO',
    company: 'Wipro',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'srinivas-pallia',
  },
  {
    firstName: 'C.',
    lastName: 'Vijayakumar',
    title: 'CEO',
    company: 'HCLTech',
    location: 'Noida, Uttar Pradesh, India',
    linkedinSlug: 'cvijayakumar',
  },
  {
    firstName: 'K.',
    lastName: 'Krithivasan',
    title: 'CEO',
    company: 'Tata Consultancy Services',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'kkrithivasan',
  },
  {
    firstName: 'Natarajan',
    lastName: 'Chandrasekaran',
    title: 'Chairman',
    company: 'Tata Sons',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'n-chandrasekaran',
  },
  {
    firstName: 'Mukesh',
    lastName: 'Ambani',
    title: 'Chairman and Managing Director',
    company: 'Reliance Industries',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'mukesh-ambani',
  },
  {
    firstName: 'Gautam',
    lastName: 'Adani',
    title: 'Chairman',
    company: 'Adani Group',
    location: 'Ahmedabad, Gujarat, India',
    linkedinSlug: 'gautam-adani',
  },
  {
    firstName: 'Uday',
    lastName: 'Kotak',
    title: 'Managing Director',
    company: 'Kotak Mahindra Bank',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'udaykotak',
  },
  {
    firstName: 'Sashidhar',
    lastName: 'Jagdishan',
    title: 'Managing Director',
    company: 'HDFC Bank',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'sashidhar-jagdishan',
  },
  {
    firstName: 'Anant',
    lastName: 'Goenka',
    title: 'Managing Director',
    company: 'CEAT',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'anant-goenka',
  },
  {
    firstName: 'Piyush',
    lastName: 'Gupta',
    title: 'CEO',
    company: 'DBS Bank',
    location: 'Singapore',
    linkedinSlug: 'piyush-gupta-dbs',
  },
  {
    firstName: 'Falguni',
    lastName: 'Nayar',
    title: 'CEO',
    company: 'Nykaa',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'falguni-nayar',
  },
  {
    firstName: 'Deepinder',
    lastName: 'Goyal',
    title: 'CEO',
    company: 'Zomato',
    location: 'Gurugram, Haryana, India',
    linkedinSlug: 'deepinder-goyal',
  },
  {
    firstName: 'Bhavish',
    lastName: 'Aggarwal',
    title: 'CEO',
    company: 'Ola',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'bhavish-aggarwal',
  },
  {
    firstName: 'Harshil',
    lastName: 'Mathur',
    title: 'CEO',
    company: 'Razorpay',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'harshilmathur',
  },
  {
    firstName: 'Kunal',
    lastName: 'Shah',
    title: 'Founder',
    company: 'CRED',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'kunalshah1',
  },
  {
    firstName: 'Vijay',
    lastName: 'Shekhar Sharma',
    title: 'Founder and CEO',
    company: 'Paytm',
    location: 'Noida, Uttar Pradesh, India',
    linkedinSlug: 'vijayshekharsharma',
  },
  {
    firstName: 'Ritesh',
    lastName: 'Agarwal',
    title: 'Founder and CEO',
    company: 'OYO',
    location: 'Gurugram, Haryana, India',
    linkedinSlug: 'riteshagar',
  },
  {
    firstName: 'Peyush',
    lastName: 'Bansal',
    title: 'CEO',
    company: 'Lenskart',
    location: 'Gurugram, Haryana, India',
    linkedinSlug: 'peyushbansal',
  },
  {
    firstName: 'Gaurav',
    lastName: 'Munjal',
    title: 'CEO',
    company: 'Unacademy',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'gauravmunjal',
  },
  {
    firstName: 'Nithin',
    lastName: 'Kamath',
    title: 'CEO',
    company: 'Zerodha',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'nithin-kamath',
  },
  {
    firstName: 'Sachin',
    lastName: 'Bansal',
    title: 'Founder',
    company: 'Navi',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'sachinbansal',
  },
  {
    firstName: 'Binny',
    lastName: 'Bansal',
    title: 'Founder',
    company: 'xto10x',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'binnybansal',
  },
  {
    firstName: 'Byju',
    lastName: 'Raveendran',
    title: 'Founder',
    company: "BYJU'S",
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'byjuraveendran',
  },
  {
    firstName: 'Namita',
    lastName: 'Thapar',
    title: 'Executive Director',
    company: 'Emcure Pharmaceuticals',
    location: 'Pune, Maharashtra, India',
    linkedinSlug: 'namita-thapar',
  },
  {
    firstName: 'Anupam',
    lastName: 'Mittal',
    title: 'Founder and CEO',
    company: 'People Group',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'anupammittal',
  },
  {
    firstName: 'Aman',
    lastName: 'Gupta',
    title: 'Co-founder and CMO',
    company: 'boAt',
    location: 'New Delhi, Delhi, India',
    linkedinSlug: 'aman-gupta-boat',
  },
  {
    firstName: 'Ashneer',
    lastName: 'Grover',
    title: 'Founder',
    company: 'Third Unicorn',
    location: 'New Delhi, Delhi, India',
    linkedinSlug: 'ashneergrover',
  },
  {
    firstName: 'Nikhil',
    lastName: 'Kamath',
    title: 'Co-founder',
    company: 'True Beacon',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'nikhilkamathcio',
  },
  {
    firstName: 'Girish',
    lastName: 'Mathrubootham',
    title: 'CEO',
    company: 'Freshworks',
    location: 'San Mateo, California, United States',
    linkedinSlug: 'girish',
  },
  {
    firstName: 'Sridhar',
    lastName: 'Vembu',
    title: 'CEO',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu, India',
    linkedinSlug: 'sridhar-vembu',
  },
  {
    firstName: 'Bhavin',
    lastName: 'Turakhia',
    title: 'Founder',
    company: 'Flock',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'bhavint',
  },
  {
    firstName: 'Divyank',
    lastName: 'Turakhia',
    title: 'Founder',
    company: 'Media.net',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'divyank',
  },
  {
    firstName: 'Rohan',
    lastName: 'Verma',
    title: 'CEO',
    company: 'MapmyIndia',
    location: 'New Delhi, Delhi, India',
    linkedinSlug: 'rohan-verma-mapmyindia',
  },
  {
    firstName: 'Sanjeev',
    lastName: 'Bikhchandani',
    title: 'Founder',
    company: 'Info Edge',
    location: 'Noida, Uttar Pradesh, India',
    linkedinSlug: 'sanjeevbikhchandani',
  },
  {
    firstName: 'Harsimarbir',
    lastName: 'Singh',
    title: 'CEO',
    company: 'Aakash Educational Services',
    location: 'New Delhi, Delhi, India',
    linkedinSlug: 'harsimarbir-singh',
  },
  {
    firstName: 'Chandra Shekhar',
    lastName: 'Ghosh',
    title: 'Managing Director',
    company: 'Bandhan Bank',
    location: 'Kolkata, West Bengal, India',
    linkedinSlug: 'chandra-shekhar-ghosh',
  },
  {
    firstName: 'Sandeep',
    lastName: 'Bakhshi',
    title: 'MD and CEO',
    company: 'ICICI Bank',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'sandeep-bakhshi',
  },
  {
    firstName: 'Rajnish',
    lastName: 'Kumar',
    title: 'Former Chairman',
    company: 'State Bank of India',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'rajnish-kumar-sbi',
  },
  {
    firstName: 'Aditya',
    lastName: 'Puri',
    title: 'Former MD',
    company: 'HDFC',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'aditya-puri',
  },
  {
    firstName: 'Kiran',
    lastName: 'Mazumdar-Shaw',
    title: 'Executive Chairperson',
    company: 'Biocon',
    location: 'Bengaluru, Karnataka, India',
    linkedinSlug: 'kiranmazumdarshaw',
  },
  {
    firstName: 'Dilip',
    lastName: 'Shanghvi',
    title: 'Managing Director',
    company: 'Sun Pharmaceutical',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'dilip-shanghvi',
  },
  {
    firstName: 'Cyrus',
    lastName: 'Mistry',
    title: 'Former Chairman',
    company: 'Tata Group',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'cyrus-mistry',
  },
  {
    firstName: 'Ratan',
    lastName: 'Tata',
    title: 'Chairman Emeritus',
    company: 'Tata Trusts',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'ratan-tata',
  },
  {
    firstName: 'Anand',
    lastName: 'Mahindra',
    title: 'Chairman',
    company: 'Mahindra Group',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'anand-mahindra',
  },
  {
    firstName: 'Kumar',
    lastName: 'Mangalam Birla',
    title: 'Chairman',
    company: 'Aditya Birla Group',
    location: 'Mumbai, Maharashtra, India',
    linkedinSlug: 'kumar-mangalam-birla',
  },
];

// Unipile fixtures first, then curated MD/CEO fillers for larger batches.
export const OUTREACH_MOCK_UPLOAD_MAX_COUNT =
  OUTREACH_MOCK_UNIPILE_RAW_PROFILES.length +
  OUTREACH_MOCK_MD_CEO_PROFILES.length;

export const resolveOutreachMockUploadCount = (
  count: number | undefined,
): number => {
  if (typeof count !== 'number' || !Number.isFinite(count)) {
    return OUTREACH_MOCK_UPLOAD_DEFAULT_COUNT;
  }

  const floored = Math.floor(count);

  if (floored < 1) {
    throw new Error('count must be at least 1');
  }

  if (floored > OUTREACH_MOCK_UPLOAD_MAX_COUNT) {
    throw new Error(`count must be at most ${OUTREACH_MOCK_UPLOAD_MAX_COUNT}`);
  }

  return floored;
};

const toFullName = (executive: OutreachMockExecutive): string =>
  `${executive.firstName} ${executive.lastName}`.replace(/\s+/g, ' ').trim();

const buildCatalogUploadPeople = ({
  count,
  projectId,
  stamp,
}: {
  count: number;
  projectId: string;
  stamp: number;
}): UploadProfilesPerson[] =>
  Array.from({ length: count }, (_, index) => {
    const executive = OUTREACH_MOCK_MD_CEO_PROFILES[index];
    const profileNumber = index + 1;
    const slug = `${executive.linkedinSlug}-mock-${stamp}-${profileNumber}`;
    const name = toFullName(executive);

    return {
      name,
      firstName: executive.firstName,
      lastName: executive.lastName,
      title: executive.title,
      headline: `${executive.title} at ${executive.company}`,
      company: executive.company,
      companyName: executive.company,
      linkedinUrl: `https://www.linkedin.com/in/${slug}`,
      linkedinProfileId: slug,
      projectId,
      location: executive.location,
    };
  });

// Unipile MD/CEO fixtures lead; fillers keep unique companies for larger counts.
export const buildOutreachMockUploadPeople = ({
  count,
  projectId,
  stamp = Date.now(),
}: {
  count: number;
  projectId: string;
  stamp?: number;
}): UploadProfilesPerson[] => {
  const unipilePeople = buildOutreachMockUnipileUploadPeople({ projectId });
  const remaining = Math.max(0, count - unipilePeople.length);

  return [
    ...unipilePeople.slice(0, count),
    ...buildCatalogUploadPeople({
      count: remaining,
      projectId,
      stamp,
    }),
  ];
};
