import { z } from 'zod';

/**
 * Zod schema for LinkedIn Recruiter People Search parameters
 */
export const recruiterPeopleSearchSchema = z.object({
  keywords: z.string().nullable(),
  locale: z.union([
    z.literal('arabic'),
    z.literal('bangla'),
    z.literal('czech'),
    z.literal('danish'),
    z.literal('german'),
    z.literal('greek'),
    z.literal('english'),
    z.literal('spanish'),
    z.literal('persian'),
    z.literal('finnish'),
    z.literal('french'),
    z.literal('hindi'),
    z.literal('hungarian'),
    z.literal('indonesian'),
    z.literal('italian'),
    z.literal('hebrew'),
    z.literal('japanese'),
    z.literal('korean'),
    z.literal('marathi'),
    z.literal('malay'),
    z.literal('dutch'),
    z.literal('norwegian'),
    z.literal('punjabi'),
    z.literal('polish'),
    z.literal('portuguese'),
    z.literal('romanian'),
    z.literal('russian'),
    z.literal('swedish'),
    z.literal('telugu'),
    z.literal('thai'),
    z.literal('tagalog'),
    z.literal('turkish'),
    z.literal('ukrainian'),
    z.literal('vietnamese'),
    z.literal('chinese_simplified'),
    z.literal('chinese_traditional'),
  ]).nullable(),
  saved_search: z.object({
    id: z.string(),
    project_id: z.string(),
  }).nullable(),
  saved_filter: z.string().nullable(),
  location: z.array(z.object({
    id: z.string(),
    priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
    scope: z.union([z.literal('CURRENT'), z.literal('OPEN_TO_RELOCATE_ONLY'), z.literal('CURRENT_OR_OPEN_TO_RELOCATE')]).nullable(),
    title: z.string().nullable(),
  })).nullable(),
  location_within_area: z.number().nullable(),
  industry: z.object({
    include: z.array(z.string()).nullable(),
    exclude: z.array(z.string()).nullable(),
  }).nullable(),
  role: z.array(z.union([
    z.object({
      id: z.string(),
      is_selection: z.boolean(),
      priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
      scope: z.union([z.literal('CURRENT_OR_PAST'), z.literal('CURRENT'), z.literal('PAST'), z.literal('PAST_NOT_CURRENT'), z.literal('OPEN_TO_WORK')]).nullable(),
    }),
    z.object({
      keywords: z.string(),
      priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
      scope: z.union([z.literal('CURRENT_OR_PAST'), z.literal('CURRENT'), z.literal('PAST'), z.literal('PAST_NOT_CURRENT'), z.literal('OPEN_TO_WORK')]).nullable(),
    }),
  ])).nullable(),
  skills: z.array(z.union([
    z.object({
      id: z.string(),
      priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
    }),
    z.object({
      keywords: z.string(),
      priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
    }),
  ])).nullable(),
  company: z.array(z.union([
    z.object({
      id: z.string(),
      name: z.string().nullable(),
      priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
      scope: z.union([z.literal('CURRENT_OR_PAST'), z.literal('CURRENT'), z.literal('PAST'), z.literal('PAST_NOT_CURRENT')]).nullable(),
    }),
    z.object({
      keywords: z.string(),
      priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
      scope: z.union([z.literal('CURRENT_OR_PAST'), z.literal('CURRENT'), z.literal('PAST'), z.literal('PAST_NOT_CURRENT')]).nullable(),
    }),
  ])).nullable(),
  company_headcount: z.array(z.object({
    min: z.union([z.literal(1), z.literal(11), z.literal(51), z.literal(201), z.literal(501), z.literal(1001), z.literal(5001), z.literal(10001)]),
    max: z.union([z.literal(10), z.literal(50), z.literal(200), z.literal(500), z.literal(1000), z.literal(5000), z.literal(10000)]),
  })).nullable(),
  current_company: z.array(z.object({
    id: z.string(),
    priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
  })).nullable(),
  past_company: z.array(z.object({
    id: z.string(),
    priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
  })).nullable(),
  school: z.array(z.object({
    id: z.string(),
    priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
  })).nullable(),
  groups: z.array(z.string()).nullable(),
  graduation_year: z.object({
    min: z.number().min(1000).max(9999).nullable(),
    max: z.number().min(1000).max(9999).nullable(),
  }).nullable(),
  tenure: z.object({
    min: z.number().nullable(),
    max: z.number().nullable(),
  }).nullable(),
  seniority: z.object({
    include: z.array(z.union([
      z.literal('owner'),
      z.literal('partner'),
      z.literal('cxo'),
      z.literal('vp'),
      z.literal('director'),
      z.literal('manager'),
      z.literal('senior'),
      z.literal('entry'),
      z.literal('training'),
      z.literal('unpaid'),
    ])).nullable(),
    exclude: z.array(z.union([
      z.literal('owner'),
      z.literal('partner'),
      z.literal('cxo'),
      z.literal('vp'),
      z.literal('director'),
      z.literal('manager'),
      z.literal('senior'),
      z.literal('entry'),
      z.literal('training'),
      z.literal('unpaid'),
    ])).nullable(),
  }).nullable(),
  function: z.array(z.string()).nullable(),
  network_distance: z.array(z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal('GROUP'),
  ])).nullable(),
  spoken_languages: z.array(z.object({
    language: z.string(),
    priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
    scope: z.union([z.literal('ELEMENTARY'), z.literal('LIMITED_WORKING'), z.literal('PROFESSIONAL_WORKING'), z.literal('FULL_PROFESSIONAL'), z.literal('NATIVE_OR_BILINGUAL')]).nullable(),
  })).nullable(),
  hide_previously_viewed: z.object({
    timespan: z.number(),
  }).nullable(),
  profile_language: z.array(z.string()).nullable(),
  recently_joined: z.array(z.object({
    min: z.union([z.literal(2), z.literal(8), z.literal(15), z.literal(31)]),
    max: z.union([z.literal(1), z.literal(7), z.literal(14), z.literal(30), z.literal(90)]),
  })).nullable(),
  spotlights: z.array(z.union([
    z.literal('OPEN_TO_WORK'),
    z.literal('ACTIVE_TALENT'),
    z.literal('REDISCOVERED_CANDIDATES'),
    z.literal('INTERNAL_CANDIDATES'),
    z.literal('INTERESTED_IN_YOUR_COMPANY'),
    z.literal('HAVE_COMPANY_CONNECTIONS'),
  ])).nullable(),
  first_name: z.array(z.string()).nullable(),
  last_name: z.array(z.string()).nullable(),
  has_military_background: z.boolean().nullable(),
  past_applicants: z.boolean().nullable(),
  hiring_projects: z.object({
    include: z.array(z.string()).nullable(),
    exclude: z.array(z.string()).nullable(),
  }).nullable(),
  recruiting_activity: z.array(z.object({
    id: z.union([z.literal('messages'), z.literal('tags'), z.literal('notes'), z.literal('projects'), z.literal('resumes'), z.literal('reviews')]),
    priority: z.union([z.literal('CAN_HAVE'), z.literal('MUST_HAVE'), z.literal('DOESNT_HAVE')]).nullable(),
    timespan: z.number().nullable(),
  })).nullable(),
  notes: z.array(z.string()).nullable(),
});
