import { STANDARD_OBJECTS } from 'twenty-shared/metadata';

import { CommandMenuItemAvailabilityType } from 'src/engine/metadata-modules/command-menu-item/enums/command-menu-item-availability-type.enum';
import { EngineComponentKey } from 'src/engine/metadata-modules/command-menu-item/enums/engine-component-key.enum';

const CANDIDATE_SELECTION =
  'numberOfSelectedRecords >= 1 and objectMetadataItem.nameSingular == "candidate" and (isSelectAll or noneDefined(selectedRecords, "deletedAt"))';

const PROJECT_SELECTION =
  'numberOfSelectedRecords >= 1 and objectMetadataItem.nameSingular == "project" and (isSelectAll or noneDefined(selectedRecords, "deletedAt"))';

const PERSON_SELECTION =
  'numberOfSelectedRecords >= 1 and (isSelectAll or noneDefined(selectedRecords, "deletedAt"))';

const VIDEO_INTERVIEW_SELECTION =
  'numberOfSelectedRecords >= 1 and objectMetadataItem.nameSingular == "videoInterview" and (isSelectAll or noneDefined(selectedRecords, "deletedAt"))';

const PHONE_CALL_SELECTION =
  'numberOfSelectedRecords >= 1 and objectMetadataItem.nameSingular == "phoneCall" and (isSelectAll or noneDefined(selectedRecords, "deletedAt"))';

// Seeded onto Twenty Standard app; scoped via conditionalAvailabilityExpression
// (candidate/project/videoInterview/phoneCall are Arxena objects without standard UIDs here).
export const ARXENA_STANDARD_COMMAND_MENU_ITEMS = {
  arxCloneCandidate: {
    universalIdentifier: 'c9308379-a8fc-5948-a847-97558e37e0d5',
    label: 'Clone multiple',
    icon: 'IconCopy',
    isPinned: false,
    position: 200,
    shortLabel: 'Clone',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_CLONE_MULTIPLE_RECORDS,
    hotKeys: null,
  },
  arxCreateVintLink: {
    universalIdentifier: '983789e4-bf17-510f-a72a-686644fe0fca',
    label: 'Create Video Interview Link',
    icon: 'IconVideo',
    isPinned: false,
    position: 201,
    shortLabel: 'Create VINT Link',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_CREATE_VINT_LINK,
    hotKeys: null,
  },
  arxShareVintLinkCandidate: {
    universalIdentifier: 'c446a9e6-d8a2-5838-9f51-b3000e4d73c2',
    label: 'Share Video Interview Link',
    icon: 'IconVideo',
    isPinned: false,
    position: 202,
    shortLabel: 'Share VINT Link',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_SHARE_VINT_LINK,
    hotKeys: null,
  },
  arxStartChat: {
    universalIdentifier: '3ea213a2-a5e0-5d26-9c9b-92b884c39f26',
    label: 'Start Chat with Candidates',
    icon: 'IconMessageCircle',
    isPinned: false,
    position: 203,
    shortLabel: 'Start Chat',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_START_CHAT_WITH_CANDIDATES,
    hotKeys: null,
  },
  arxStopChat: {
    universalIdentifier: '82469116-7fb6-5b93-93df-cbcc4501b152',
    label: 'Stop Chat with Candidates',
    icon: 'IconMessageX',
    isPinned: false,
    position: 204,
    shortLabel: 'Stop Chat',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_STOP_CHAT_WITH_CANDIDATES,
    hotKeys: null,
  },
  arxUpdateMessagingChannel: {
    universalIdentifier: 'fc3c9701-21ce-5f18-8afc-9f4ec92b8797',
    label: 'Update messaging channel',
    icon: 'IconMessages',
    isPinned: false,
    position: 205,
    shortLabel: 'Update channel',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey:
      EngineComponentKey.ARX_UPDATE_MESSAGING_CHANNEL_FOR_CANDIDATES,
    hotKeys: null,
  },
  arxMoveCandidatesToProject: {
    universalIdentifier: 'e217423b-484b-5723-9da8-f5e545546f86',
    label: 'Move candidates to another project',
    icon: 'IconBriefcase',
    isPinned: false,
    position: 206,
    shortLabel: 'Move to project',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey:
      EngineComponentKey.ARX_MOVE_CANDIDATES_TO_ANOTHER_PROJECT,
    hotKeys: null,
  },
  arxRefreshChatStatus: {
    universalIdentifier: 'ca1098d6-d56f-5898-96d6-74281d850d55',
    label: 'Refresh Chat Status',
    icon: 'IconRefresh',
    isPinned: false,
    position: 207,
    shortLabel: 'Refresh Chat Status',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_REFRESH_CHAT_STATUS,
    hotKeys: null,
  },
  arxRefreshChatCount: {
    universalIdentifier: 'ebbad72c-a6ae-5717-bec2-657333e74cd1',
    label: 'Refresh Chat Counts',
    icon: 'IconRefresh',
    isPinned: false,
    position: 208,
    shortLabel: 'Refresh Chat Counts',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_REFRESH_CHAT_COUNT,
    hotKeys: null,
  },
  arxPopulateShortlist: {
    universalIdentifier: 'e8ffb95c-bef5-53c9-a92d-9edbb659cf4c',
    label: 'Populate Shortlist Records',
    icon: 'IconList',
    isPinned: false,
    position: 209,
    shortLabel: 'Populate Shortlist',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_POPULATE_SHORTLIST,
    hotKeys: null,
  },
  arxShareChatBasedShortlist: {
    universalIdentifier: 'cbc17f0f-4957-56eb-99f4-17ea46ad4a80',
    label: 'Share Chat Based Shortlist',
    icon: 'IconShare',
    isPinned: false,
    position: 210,
    shortLabel: 'Share Chat Shortlist',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_SHARE_CHAT_BASED_SHORTLIST,
    hotKeys: null,
  },
  arxUpdateSnapshotProfiles: {
    universalIdentifier: '7d45fedf-267c-53b1-844a-4ee59726f87a',
    label: 'Save Resumes & Contacts from Portals',
    icon: 'IconRefresh',
    isPinned: true,
    position: 211,
    shortLabel: 'Save Resumes & Contacts from Portals',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey:
      EngineComponentKey.ARX_UPDATE_SNAPSHOT_PROFILES_FROM_JOB_BOARDS,
    hotKeys: null,
  },
  arxChatAndVintShortlist: {
    universalIdentifier: 'ae0914ec-dbdd-55e2-b0ff-4def73dcd4b1',
    label: 'Create Shortlist PDF and Excel',
    icon: 'IconShare',
    isPinned: false,
    position: 212,
    shortLabel: 'Create Shortlist PDF and Excel',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey:
      EngineComponentKey.ARX_CHAT_AND_VIDEO_INTERVIEW_SHORTLIST,
    hotKeys: null,
  },
  arxDownloadShortlist: {
    universalIdentifier: '2add3d88-c5f5-5397-854c-5f7f51d10143',
    label: 'Download Shortlist',
    icon: 'IconDownload',
    isPinned: false,
    position: 213,
    shortLabel: 'Download Shortlist',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_DOWNLOAD_SHORTLIST,
    hotKeys: null,
  },
  arxSendToWhatsapp: {
    universalIdentifier: '7bc389df-e55b-592c-aafb-c0c093ee76fe',
    label: 'Send to Whatsapp Chrome Extension',
    icon: 'IconShare',
    isPinned: false,
    position: 214,
    shortLabel: 'Send to Whatsapp Chrome Extension',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_SEND_TO_WHATSAPP,
    hotKeys: null,
  },
  arxDeleteCandidatesAndPeople: {
    universalIdentifier: '050a934f-41a3-5aa5-9733-eecd29f76a2c',
    label: 'Delete Candidates and People',
    icon: 'IconTrashX',
    isPinned: false,
    position: 215,
    shortLabel: 'Delete Candidates and People',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_DELETE_CANDIDATES_AND_PEOPLE,
    hotKeys: null,
  },
  arxDownloadCandidateCvs: {
    universalIdentifier: 'efedf4a4-5859-51ab-99de-e7ce0ada9aba',
    label: 'Download Candidate CVs',
    icon: 'IconDownload',
    isPinned: false,
    position: 216,
    shortLabel: 'Download CVs',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_DOWNLOAD_CANDIDATE_CVS,
    hotKeys: null,
  },
  arxAddToGoogleContacts: {
    universalIdentifier: 'c1a7097b-b63f-5326-9d05-9467bf01ff4b',
    label: 'Add to Google Contacts',
    icon: 'IconMail',
    isPinned: false,
    position: 217,
    shortLabel: 'Add to Google Contacts',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_ADD_TO_GOOGLE_CONTACTS,
    hotKeys: null,
  },
  arxRestartMsgs: {
    universalIdentifier: 'de48d3cb-36af-57de-b1a1-f237b532342d',
    label: 'Reminder (remind) Messaging for Candidates',
    icon: 'IconRefresh',
    isPinned: true,
    position: 218,
    shortLabel: 'Reminder (remind) Messaging for Candidates',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_RESTART_MSGS,
    hotKeys: null,
  },
  arxResetMsgsFromWhatsapp: {
    universalIdentifier: '52cb0095-3b26-5014-9e2f-4cd4fc6220c3',
    label: 'Reset Messages in Whatsapp',
    icon: 'IconTrashOff',
    isPinned: false,
    position: 219,
    shortLabel: 'Reset Messages in Whatsapp',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_RESET_MSGS_FROM_WHATSAPP,
    hotKeys: null,
  },
  arxSyncChatsWithWhatsapp: {
    universalIdentifier: '01d7d765-a2a0-50be-a2ee-5ef0dab9b0d7',
    label: 'Sync Chats with WhatsApp',
    icon: 'IconRefresh',
    isPinned: true,
    position: 220,
    shortLabel: 'Sync Chats with WhatsApp',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_SYNC_CHATS_WITH_WHATSAPP,
    hotKeys: null,
  },
  arxDownloadAsExcel: {
    universalIdentifier: '7cb25e09-8d26-514e-96ca-e61f8eeedfda',
    label: 'Download selected as Excel',
    icon: 'IconDownload',
    isPinned: false,
    position: 221,
    shortLabel: 'Download selected as Excel',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_DOWNLOAD_AS_EXCEL,
    hotKeys: null,
  },
  arxCheckContactAvailability: {
    universalIdentifier: '8f28824f-f924-50d4-b050-7898512c17f8',
    label: 'Check Contact Availability',
    icon: 'IconPhone',
    isPinned: false,
    position: 222,
    shortLabel: 'Check Availability',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_CHECK_CONTACT_AVAILABILITY,
    hotKeys: null,
  },
  arxFetchContactDetails: {
    universalIdentifier: '41ab885e-235c-55bb-b65e-a23c85d58b24',
    label: 'Fetch Contact Details',
    icon: 'IconPhone',
    isPinned: false,
    position: 223,
    shortLabel: 'Fetch Contacts',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: CANDIDATE_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_FETCH_CONTACT_DETAILS,
    hotKeys: null,
  },
  arxCloneProject: {
    universalIdentifier: '0e2b6828-6e88-5ac5-b4e3-6a542dd72642',
    label: 'Clone multiple',
    icon: 'IconCopy',
    isPinned: true,
    position: 230,
    shortLabel: 'Clone',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: PROJECT_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_CLONE_MULTIPLE_RECORDS,
    hotKeys: null,
  },
  arxCreateInterviewerAvatarVideos: {
    universalIdentifier: 'bd6135ae-947b-5b9a-a835-6fcce631f22d',
    label: 'Create Interviewer Avatar Videos',
    icon: 'IconList',
    isPinned: true,
    position: 231,
    shortLabel: 'Create Interviewer Avatar Videos',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: PROJECT_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_CREATE_INTERVIEWER_AVATAR_VIDEOS,
    hotKeys: null,
  },
  arxCheckDataIntegrityOfProject: {
    universalIdentifier: '26b4bd6c-be48-55b1-9532-8236bd37a06f',
    label: 'Check Data Integrity of Project',
    icon: 'IconList',
    isPinned: true,
    position: 232,
    shortLabel: 'Check Data Integrity of Project',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: PROJECT_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_CHECK_DATA_INTEGRITY_OF_PROJECT,
    hotKeys: null,
  },
  arxClonePerson: {
    universalIdentifier: 'a4614257-6322-5f42-99de-96e9de4c1178',
    label: 'Clone multiple',
    icon: 'IconCopy',
    isPinned: true,
    position: 240,
    shortLabel: 'Clone',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: PERSON_SELECTION,
    availabilityObjectMetadataUniversalIdentifier:
      STANDARD_OBJECTS.person.universalIdentifier,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_CLONE_MULTIPLE_RECORDS,
    hotKeys: null,
  },
  arxDeleteCandidatesAndPeoplePerson: {
    universalIdentifier: 'ff13ae13-5979-5520-b628-547c11beebac',
    label: 'Delete Candidates and People',
    icon: 'IconList',
    isPinned: false,
    position: 241,
    shortLabel: 'Delete Candidates and People',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: PERSON_SELECTION,
    availabilityObjectMetadataUniversalIdentifier:
      STANDARD_OBJECTS.person.universalIdentifier,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_DELETE_CANDIDATES_AND_PEOPLE,
    hotKeys: null,
  },
  arxCloneVideoInterview: {
    universalIdentifier: '3f3bd70a-a3ec-5c65-925c-1e7b3dc0df73',
    label: 'Clone multiple',
    icon: 'IconCopy',
    isPinned: true,
    position: 250,
    shortLabel: 'Clone',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: VIDEO_INTERVIEW_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_CLONE_MULTIPLE_RECORDS,
    hotKeys: null,
  },
  arxShareVintLinkVideoInterview: {
    universalIdentifier: '3b401259-9bab-5cfa-9651-d7839c9e02f5',
    label: 'Share Video Interview Link With Candidate',
    icon: 'IconList',
    isPinned: false,
    position: 251,
    shortLabel: 'Share Video Interview Link with Candidate',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: VIDEO_INTERVIEW_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_SHARE_VINT_LINK,
    hotKeys: null,
  },
  arxClonePhoneCall: {
    universalIdentifier: '11a57a4f-e89a-54ce-8dba-ed5e23396fbe',
    label: 'Clone multiple',
    icon: 'IconCopy',
    isPinned: true,
    position: 260,
    shortLabel: 'Clone',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: PHONE_CALL_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_CLONE_MULTIPLE_RECORDS,
    hotKeys: null,
  },
  arxTranscribeCall: {
    universalIdentifier: '5c9c2b58-cc9f-5893-a182-4b6824fa45aa',
    label: 'Transcribe Call',
    icon: 'IconList',
    isPinned: false,
    position: 261,
    shortLabel: 'Transcribe Call',
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    conditionalAvailabilityExpression: PHONE_CALL_SELECTION,
    availabilityObjectMetadataUniversalIdentifier: null,
    frontComponentUniversalIdentifier: null,
    engineComponentKey: EngineComponentKey.ARX_TRANSCRIBE_CALL,
    hotKeys: null,
  },
} as const;
