export enum WorkflowActionType {
  CODE = 'CODE',
  SEND_EMAIL = 'SEND_EMAIL',
  CREATE_RECORD = 'CREATE_RECORD',
  UPDATE_RECORD = 'UPDATE_RECORD',
  DELETE_RECORD = 'DELETE_RECORD',
  FIND_RECORDS = 'FIND_RECORDS',
  FILTER = 'FILTER',
  IF_ELSE = 'IF_ELSE',
  ITERATOR = 'ITERATOR',
  AI_AGENT = 'AI_AGENT',
  EMPTY = 'EMPTY',
  DELAY = 'DELAY',
}
