const stringifyForPrompt = (value: unknown): string => {
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
};

export const buildIcpExtractionPrompt = (input: {
  personProfile: Record<string, unknown>;
  companyProfile: Record<string, unknown> | null;
  postsSummary?: string;
}): string => {
  const postsSection = input.postsSummary?.trim()
    ? ['', 'Recent LinkedIn posts by this person:', input.postsSummary.trim()]
    : [];

  const companySection = input.companyProfile
    ? `Company profile: ${stringifyForPrompt(input.companyProfile)}`
    : [
        'Company profile: NOT AVAILABLE — no LinkedIn company page could be',
        "loaded for this person's company. Infer what the company sells from",
        "the person's headline, summary, and current-role description in the",
        'person profile (and posts, if provided). Be conservative: if those',
        'do not indicate a sellable product or service, mark the recipient',
        'not relevant rather than inventing an offering.',
      ].join('\n');

  return [
    'You are screening a cold-outreach lead to decide whether a specific',
    'tactic — a "target-account org chart lure" — will land with them,',
    'and if so, what to build and which pitch angle to use.',
    '',
    'CONTEXT: What a target-account lure is.',
    'Instead of a generic cold-email pitch, the first line offers the',
    'recipient something concretely useful and unfakeable: a free, real',
    'org chart (reporting lines, function heads) of ONE SPECIFIC COMPANY',
    'the recipient is already trying to reach. It only works because it',
    'could not have been mass-sent — it proves real work was done on this',
    "exact recipient's world, not a template. Two things must be true",
    'for it to land:',
    '(a) The recipient PERSONALLY consumes account-level intelligence',
    '    about specific target companies. There are two distinct motions',
    '    that qualify — a person needs only ONE of them:',
    '    - SELLING motion: they personally pursue and close deals at',
    '      target accounts (founder, AE, sales/BD/growth/partnerships,',
    '      or a technical co-founder at a small team where everyone',
    '      sells). Their problem is MULTI-THREADING: mapping the buying',
    '      committee inside deals they are already in, avoiding being',
    '      single-threaded through one champion.',
    '    - TARGETING motion: they personally own account selection and',
    '      persona mapping for outbound or account-based campaigns',
    '      (ABM lead, demand-gen/growth-marketing leader running',
    '      account-based programs, SDR/BDR leadership, RevOps owning',
    '      target lists, outbound lead-gen agency operators). Their',
    '      problem is TARGETING: choosing the right accounts and the',
    '      right people/personas inside them before any campaign runs.',
    "(b) The org chart has to map to the function that the recipient's",
    '    own product would actually be sold to at a target company — a',
    '    chart of the Sales org is useless to someone selling an SRE',
    '    tool; they need the Engineering/Platform org instead. For a',
    '    TARGETING-motion recipient, the chart should cover the buying',
    '    committee their campaigns try to penetrate (economic buyer,',
    '    technical buyer, end users of what THEIR company sells).',
    '',
    "Given this person's LinkedIn profile and their company's LinkedIn",
    'profile, determine:',
    '',
    "1. What does this person's company actually sell (product, category)?",
    '2. Who would THAT company want to reach as a customer — industry,',
    '   company size range, likely tech stack signals, and the specific',
    '   job title(s) that would be the buyer or economic buyer.',
    '3. Is this specific person plausibly a personal consumer of a',
    '   target-account org chart, via EITHER motion above?',
    '   TRUE via SELLING motion if: founder/co-founder (especially at a',
    '   company small enough that founders still sell personally — check',
    '   employee_count), an explicit sales/BD/growth/partnerships title,',
    '   a LinkedIn summary that reads like outbound sales copy (pitches',
    '   the product, ends with a call to connect), or job history with',
    '   revenue-facing or quota-carrying responsibility.',
    '   TRUE via TARGETING motion if: the profile shows they personally',
    '   design or operate account-based or outbound programs — explicit',
    '   ABM ownership, target-account list building, ICP definition,',
    '   buying-committee or persona mapping, use of prospecting/intent',
    '   data tools (e.g. Apollo, ZoomInfo, Clay, 6sense, Sales Nav) to',
    '   pick accounts and people, or leadership of SDR/outbound teams.',
    '   A marketing title alone is NOT sufficient — the account-level',
    '   signal must be present. Note: creating pipeline through',
    '   marketing rather than closing it is NOT disqualifying; for the',
    '   TARGETING motion it is precisely the qualifying behavior.',
    '   FALSE if: a pure technical/operational IC role with no sales or',
    '   account-targeting signal anywhere in the profile, especially at',
    '   a company with 200+ employees (apply this threshold literally —',
    '   do not invoke it below ~200) where they have no evident tie to',
    '   the revenue motion; a function unrelated to revenue (HR, Legal,',
    '   back-office Finance) with no contrary evidence; or a marketer',
    '   whose work is entirely brand/content/comms/paid-media at the',
    '   segment level with no account-based or outbound component.',
    '   AMBIGUOUS cases (e.g. a technical co-founder, a "Head of X"',
    '   title that could include BD, a generalist marketer who might',
    '   run ABM): lean TRUE if the company is small/early enough that',
    "   role specialization hasn't happened yet — but say so explicitly",
    '   in your reasoning. Do not default to TRUE to be more useful to',
    '   the caller; an incorrect TRUE wastes a send on the wrong lure',
    '   entirely, which is worse than a correct FALSE.',
    '4. If TRUE: which motion applies — "selling", "targeting", or',
    '   "both" (e.g. a founder who both runs ABM and closes deals).',
    '   This drives the pitch angle downstream: selling → multi-',
    '   threading/buying-committee framing; targeting → account and',
    '   persona selection framing. If FALSE, leave this null.',
    '5. If TRUE: what specific function/team, at a target company,',
    '   should the org chart focus on to be useful to this person?',
    "   Anchor this to what their company sells (step 1) — e.g. a",
    '   security product → chart the Security/IT function at the',
    '   target; an SRE tool → chart Engineering/Platform; a sales tool',
    '   → chart Sales/RevOps; an ERP/CRM implementation service →',
    '   chart IT/Enterprise Applications. For a TARGETING-motion',
    '   recipient, the chart function should match the buyer_titles',
    '   from step 2 (the buying committee their campaigns target).',
    '   If FALSE, leave this null.',
    '',
    `Person profile: ${stringifyForPrompt(input.personProfile)}`,
    companySection,
    ...postsSection,
    '',
    'Output as JSON only, no other text:',
    '{',
    '  "sells": "...",',
    '  "relevant_recipient_for_target_account_lure": true/false,',
    '  "lure_motion": "selling" | "targeting" | "both" | null,',
    '  "reasoning": "... — must explicitly justify the true/false call',
    '    from step 3, name which motion(s) the evidence supports and',
    '    which signals triggered it, not just restate the person\'s',
    '    title",',
    '  "icp": {',
    '    "industry": [...],',
    '    "employee_range": "...",',
    '    "tech_stack_signals": [...],',
    '    "buyer_titles": [...],',
    '    "pain_signals": [...]',
    '  },',
    '  "chart_function": "..." or null',
    '}',
  ].join('\n');
};