

export async function checkIfResponseMessageSoundsHumanLike(responseMessage:{content:string|null}){
    let responseMessageType :string = "seemsHumanMessage"
    try{
      console.log("Going to check if response message sounds human like or not")
      console.log("the response message is actually:", responseMessage?.content)
      if (responseMessage?.content != null && responseMessage?.content != "" ){
        const checkBotTypeMessages = [{ role: 'system', content: "Does the sentence below seem like it has been generated by a llm? If the sentence has words wrapped between asterisks ** for bold or has words like I am updating your profile or has words in square brackets like [share_jd], then it is generated by a bot and return 'yes'.  return only either 'yes' or 'no'. Return in the json format of  {'isLikeBot':'no'}. No explanation necessary" }, {role:'user', content:responseMessage.content}];
        // @ts-ignore
        const response = await this.openAIclient.chat.completions.create({ model: modelName, messages: checkBotTypeMessages, response_format:{ type: "json_object" }, });
        const LLMMessage:string =  response.choices[0].message.content || ""
        console.log("The BOT MESSAGE SOUNDS like ::::",response.choices[0].message.content)
        if (LLMMessage==="" ){
          responseMessageType = "seemsHumanMessage"
        } else {
          const isLikeBot = JSON.parse(LLMMessage)["isLikeBot"]
          if (isLikeBot === "no" || isLikeBot === "No" ){
            responseMessageType = "seemsHumanMessage"
          }
          else if (isLikeBot === "yes" || isLikeBot === "Yes" ){
            console.log("THe message does sound like a bot:", responseMessage.content)
            responseMessageType = "seemsBotMessage"
          }
          console.log("Check bot response yes/ no:",isLikeBot)
        }
        console.log("Finally response message type  ",responseMessageType )
      }
      else{
        console.log("REsponse message is either null or is empty string", responseMessage?.content)
        responseMessageType = "seemsHumanMessage"
      }
    }
    catch{
      console.log("responseMessage Type to check if HUman Message has been created is an error:", responseMessageType)
      responseMessageType = "seemsHumanMessage"
    }
    return responseMessageType
  }

