export const GTM_SEARCH_PEOPLE_FOR_COMPANY_LOGIC_FUNCTION_NAME =
  'search-people-for-company';
export const GTM_FETCH_LINKEDIN_PROFILE_LOGIC_FUNCTION_NAME =
  'fetch-linkedin-profile';
export const GTM_SEARCH_PEOPLE_LOGIC_FUNCTION_NAME = 'search-people';
export const GTM_SEARCH_COMPANIES_LOGIC_FUNCTION_NAME = 'search-companies';
export const GTM_SEARCH_JOBS_LOGIC_FUNCTION_NAME = 'search-jobs';
export const GTM_SEARCH_POSTS_LOGIC_FUNCTION_NAME = 'search-posts';
export const GTM_FETCH_LINKEDIN_MESSAGES_LOGIC_FUNCTION_NAME =
  'fetch-linkedin-messages';
export const GTM_FETCH_COMPANY_DETAILS_LOGIC_FUNCTION_NAME =
  'fetch-company-details';
export const GTM_UPLOAD_PROFILES_LOGIC_FUNCTION_NAME = 'upload-profiles';

export const GTM_NATIVE_LOGIC_FUNCTION_NAMES = new Set([
  GTM_SEARCH_PEOPLE_FOR_COMPANY_LOGIC_FUNCTION_NAME,
  GTM_FETCH_LINKEDIN_PROFILE_LOGIC_FUNCTION_NAME,
  GTM_SEARCH_PEOPLE_LOGIC_FUNCTION_NAME,
  GTM_SEARCH_COMPANIES_LOGIC_FUNCTION_NAME,
  GTM_SEARCH_JOBS_LOGIC_FUNCTION_NAME,
  GTM_SEARCH_POSTS_LOGIC_FUNCTION_NAME,
  GTM_FETCH_LINKEDIN_MESSAGES_LOGIC_FUNCTION_NAME,
  GTM_FETCH_COMPANY_DETAILS_LOGIC_FUNCTION_NAME,
  GTM_UPLOAD_PROFILES_LOGIC_FUNCTION_NAME,
]);
