export const OUTREACH_SEARCH_PEOPLE_FOR_COMPANY_LOGIC_FUNCTION_NAME =
  'search-people-for-company';
export const OUTREACH_FETCH_LINKEDIN_PROFILE_LOGIC_FUNCTION_NAME =
  'fetch-linkedin-profile';
/** Native workflow LF — not the LLM `search` skill. */
export const OUTREACH_SEARCH_PEOPLE_LOGIC_FUNCTION_NAME = 'search-people';
/** Native harvest LF — not the LLM `search` skill. */
export const OUTREACH_SEARCH_COMPANIES_LOGIC_FUNCTION_NAME = 'search-companies';
export const OUTREACH_SEARCH_JOBS_LOGIC_FUNCTION_NAME = 'search-jobs';
export const OUTREACH_SEARCH_POSTS_LOGIC_FUNCTION_NAME = 'search-posts';
export const OUTREACH_FETCH_LINKEDIN_MESSAGES_LOGIC_FUNCTION_NAME =
  'fetch-linkedin-messages';
export const OUTREACH_FETCH_COMPANY_DETAILS_LOGIC_FUNCTION_NAME =
  'fetch-company-details';
export const OUTREACH_UPLOAD_PROFILES_LOGIC_FUNCTION_NAME = 'upload-profiles';
export const OUTREACH_UPSERT_COMPANIES_LOGIC_FUNCTION_NAME = 'upsert-companies';
export const OUTREACH_ENRICH_CONTACT_LOGIC_FUNCTION_NAME = 'enrich-contact';
export const OUTREACH_GET_CALENDAR_AVAILABILITY_LOGIC_FUNCTION_NAME =
  'get-calendar-availability';
export const OUTREACH_DETECT_FAKE_PROFILES_LOGIC_FUNCTION_NAME =
  'detect-fake-profiles';
export const OUTREACH_FILTER_PROFILES_LOGIC_FUNCTION_NAME = 'filter-profiles';

export const OUTREACH_NATIVE_LOGIC_FUNCTION_NAMES = new Set([
  OUTREACH_SEARCH_PEOPLE_FOR_COMPANY_LOGIC_FUNCTION_NAME,
  OUTREACH_FETCH_LINKEDIN_PROFILE_LOGIC_FUNCTION_NAME,
  OUTREACH_SEARCH_PEOPLE_LOGIC_FUNCTION_NAME,
  OUTREACH_SEARCH_COMPANIES_LOGIC_FUNCTION_NAME,
  OUTREACH_SEARCH_JOBS_LOGIC_FUNCTION_NAME,
  OUTREACH_SEARCH_POSTS_LOGIC_FUNCTION_NAME,
  OUTREACH_FETCH_LINKEDIN_MESSAGES_LOGIC_FUNCTION_NAME,
  OUTREACH_FETCH_COMPANY_DETAILS_LOGIC_FUNCTION_NAME,
  OUTREACH_UPLOAD_PROFILES_LOGIC_FUNCTION_NAME,
  OUTREACH_UPSERT_COMPANIES_LOGIC_FUNCTION_NAME,
  OUTREACH_ENRICH_CONTACT_LOGIC_FUNCTION_NAME,
  OUTREACH_GET_CALENDAR_AVAILABILITY_LOGIC_FUNCTION_NAME,
  OUTREACH_DETECT_FAKE_PROFILES_LOGIC_FUNCTION_NAME,
  OUTREACH_FILTER_PROFILES_LOGIC_FUNCTION_NAME,
]);
