import * as fs from 'fs';
import path from 'path';

// Same cwd convention as generateBarrels.ts (repo root).
const OUTREACH_PATH = path.resolve('packages/twenty-shared/src/outreach');
const SKILLS_PATH = path.join(OUTREACH_PATH, 'skills');
const OUTPUT_PATH = path.join(
  OUTREACH_PATH,
  'outreach-skill-markdown.generated.ts',
);

const markdownFileNames = fs
  .readdirSync(SKILLS_PATH)
  .filter((fileName) => fileName.endsWith('.md'))
  .sort((a, b) => a.localeCompare(b));

const entries = markdownFileNames
  .map((fileName) => {
    const content = fs.readFileSync(path.join(SKILLS_PATH, fileName), 'utf-8');

    return `  ${JSON.stringify(path.parse(fileName).name)}: ${JSON.stringify(content)},`;
  })
  .join('\n');

const output = `/*
 * Auto-generated by scripts/generateOutreachSkills.ts from ./skills/*.md.
 * Any edits to this file will be overridden.
 */

export const OUTREACH_SKILL_MARKDOWN: Record<string, string> = {
${entries}
};
`;

fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');
