export const OUTREACH_JOURNEY_TIMELINE_STAGES = [
  { id: 'QUEUED', label: 'Queued' },
  { id: 'CONNECTION_SENT', label: 'Connection sent' },
  { id: 'CONNECTION_ACCEPTED', label: 'Connection accepted' },
  { id: 'REPLIED', label: 'Replied' },
  { id: 'WAITING_REPLY', label: 'Waiting for reply' },
  { id: 'FOLLOW_UP_1', label: 'Followed up' },
  { id: 'FOLLOW_UP_2', label: 'Followed up 2' },
  { id: 'FOLLOW_UP_3', label: 'Followed up 3' },
  { id: 'FORM_PENDING', label: 'Follow-up with action / reminder' },
  { id: 'MEETING_BOOKED', label: 'Meeting booked' },
  { id: 'FAILED_NO_REPLY', label: 'Failed no reply' },
  { id: 'DEFERRED', label: 'Waiting for slot' },
  { id: 'STOPPED', label: 'Stopped' },
] as const;
