export enum MultipleRecordsActionKeys {
  DELETE = 'delete-multiple-records',
  EXPORT = 'export-multiple-records',
  DESTROY = 'destroy-multiple-records',
  DUPLICATE = 'duplicate-multiple-records',
  CLONE = 'clone-multiple-records',
  VINT_LINK = 'create-vint-link',
  REFRESH_CHAT_STATUS = 'refresh-chat-status',
  REFRESH_CHAT_COUNT = 'refresh-chat-count',
  CREATE_SHORTLIST = 'create-shortlist',
  SHARE_VINT_LINK = 'share-vint-link',
  DELETE_CANDIDATES_AND_PEOPLE = 'delete-candidates-and-people',
  SEND_TO_WHATSAPP = 'send-to-whatsapp',
  CHAT_AND_VIDEO_INTERVIEW_SHORTLIST = 'chat-and-video-interview-shortlist',
  CREATE_CHAT_BASED_SHORTLIST = 'create-chat-based-shortlist',
  POPULATE_SHORTLIST = 'populate-shortlist',
  START_CHAT_WITH_CANDIDATES = 'start-chat-with-candidates',
  CLONE_VINT = 'CLONE_VINT',
  CLONE_PEOPLE = 'CLONE_PEOPLE',
  CLONE_VINT_INTERVIEW = 'CLONE_VINT_INTERVIEW',
  CREATE_INTERVIEWER_AVATAR_VIDEOS = 'CREATE_INTERVIEWER_AVATAR_VIDEOS',
  CHECK_DATA_INTEGRITY_OF_JOB = 'CHECK_DATA_INTEGRITY_OF_JOB',
  TRANSCRIBE_CALL = 'TRANSCRIBE_CALL',
  ENRICH_CANDIDATES = 'enrich-candidates',
  UPDATE_SNAPSHOT_PROFILES_FROM_JOB_BOARDS = 'update-snapshot-profiles-from-job-boards',
  DOWNLOAD_CANDIDATE_CVS = "download-candidate-cvs",
}
