name: 'CI Chromatic'

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'packages/twenty-front/**'
  pull_request:
    types: [labeled]
    paths:
      - 'package.json'
      - 'packages/twenty-front/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic-deployment:
    if: contains(github.event.pull_request.labels.*.name, 'run-chromatic') || github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      REACT_APP_SERVER_BASE_URL: http://127.0.0.1:3000
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Front / Write .env
        run: |
          cd packages/twenty-front
          touch .env
          echo "REACT_APP_SERVER_BASE_URL: $REACT_APP_SERVER_BASE_URL" >> .env
      - name: Publish to Chromatic
        run: |
          npx nx run twenty-front:chromatic:ci
