name: CI Front
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'packages/twenty-front/**'
      - 'packages/twenty-ui/**'
  pull_request:
    paths:
      - 'package.json'
      - 'packages/twenty-front/**'
      - 'packages/twenty-ui/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  front-sb-test:
    runs-on: ci-8-cores
    strategy:
      matrix:
        storybook_scope: [pages, modules]
    env:
      REACT_APP_SERVER_BASE_URL: http://localhost:3000
      STORYBOOK_SCOPE: ${{ matrix.storybook_scope }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Fetch local actions
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Install Playwright
        run: cd packages/twenty-front && npx playwright install
      - name: Front / Restore Storybook Task Cache
        uses: ./.github/workflows/actions/task-cache
        with:
          tag: scope:frontend
          tasks: storybook:build
          suffix: _${{ matrix.storybook_scope }}
      - name: Front / Write .env
        run: npx nx reset:env twenty-front
      - name: Run storybook tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx nx storybook:static twenty-front" \
            "npx wait-on tcp:6006 && npx nx storybook:test twenty-front"
  front-task:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, typecheck, test]
    env:
      REACT_APP_SERVER_BASE_URL: http://localhost:3000
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Fetch local actions and base branch history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Front / Restore Task Cache
        uses: ./.github/workflows/actions/task-cache
        with:
          tag: scope:frontend
          tasks: ${{ matrix.task }}
      - name: Front / Run task
        uses: ./.github/workflows/actions/nx-affected
        with:
          tag: scope:frontend
          tasks: ${{ matrix.task }}