name: CI Server
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'packages/twenty-server/**'
      - 'packages/twenty-emails/**'
  pull_request:
    paths:
      - 'package.json'
      - 'packages/twenty-server/**'
      - 'packages/twenty-emails/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  server-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: twentycrm/twenty-postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Server / Install Dependencies
        run: yarn
      - name: Server / Run linter
        run: yarn nx lint twenty-server
      - name: Server / Run jest tests
        run: yarn nx test:unit twenty-server
      - name: Server / Build
        run: yarn nx build twenty-server
      - name: Server / Write .env
        run: |
          cd packages/twenty-server
          cp .env.example .env
      - name: Worker / Run
        run: MESSAGE_QUEUE_TYPE=sync yarn nx worker twenty-server
