name: CI-Vale
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.directories.outputs.LIST }}
          fail_on_error: true
          vale_flags: '--minAlertLevel=error'
          reporter: github-pr-check
          token: ${{ github.token }}
          filter_mode: nofilter
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}